{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.3.aar",
          "url": "oboemusicplayerandrecorder-0.3.3.aar",
          "size": 1740226,
          "sha512": "41de20d4a41a38d8a5641f81af9893ece1285b3a04c292e2b8bf0ef12b70d3ad46ec8831e60fbe043915f942ca34c2fe2614f4b172c8e2aef8c2d203c5b56d10",
          "sha256": "c21790704ad903ee7f48c6e60c1886797384fc0cc4d2779ef2d8715f986c19a4",
          "sha1": "27869c98dcb6080b63d2e9cd5a861a7ae0d0c2a9",
          "md5": "5a6588bf7ebaa3e01ee8788119cd554e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.3.aar",
          "url": "oboemusicplayerandrecorder-0.3.3.aar",
          "size": 1740226,
          "sha512": "41de20d4a41a38d8a5641f81af9893ece1285b3a04c292e2b8bf0ef12b70d3ad46ec8831e60fbe043915f942ca34c2fe2614f4b172c8e2aef8c2d203c5b56d10",
          "sha256": "c21790704ad903ee7f48c6e60c1886797384fc0cc4d2779ef2d8715f986c19a4",
          "sha1": "27869c98dcb6080b63d2e9cd5a861a7ae0d0c2a9",
          "md5": "5a6588bf7ebaa3e01ee8788119cd554e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.3-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.3-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
