{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.8.2-exp",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.2-exp.aar",
          "url": "oboemusicplayerandrecorder-0.8.2-exp.aar",
          "size": 2321176,
          "sha512": "507eb66d2db64aacc621ccd4e70728c348d0a61512eb33e2c34c4992a16daa8e029a25269b3e5edf83cb6d2047e3bf257129197cbdfeb7959f538291380fa5c9",
          "sha256": "dc6dad59dc58d81d6a39e4b004b219d5ade268432da9357d8a4934c91e553f06",
          "sha1": "b818418838f7dc556cda6626b580c04a05a1ebe0",
          "md5": "8eb1885a38a2ef20edbcf6ac7d7130d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.2-exp.aar",
          "url": "oboemusicplayerandrecorder-0.8.2-exp.aar",
          "size": 2321176,
          "sha512": "507eb66d2db64aacc621ccd4e70728c348d0a61512eb33e2c34c4992a16daa8e029a25269b3e5edf83cb6d2047e3bf257129197cbdfeb7959f538291380fa5c9",
          "sha256": "dc6dad59dc58d81d6a39e4b004b219d5ade268432da9357d8a4934c91e553f06",
          "sha1": "b818418838f7dc556cda6626b580c04a05a1ebe0",
          "md5": "8eb1885a38a2ef20edbcf6ac7d7130d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.2-exp-sources.jar",
          "url": "oboemusicplayerandrecorder-0.8.2-exp-sources.jar",
          "size": 25250,
          "sha512": "0567f5f8407f7feb34d05fcedd5c359a4cc15cbab80bb216aaf9fe810db2a3a84b3e9c0e96bc3b845dba3b9d7f2cfdfb50d0c1485b3b2f3a10b384d29dc09d80",
          "sha256": "db63f13a661665659a29bedd86d78c96e6f51679a6282436a475bf11253a37ae",
          "sha1": "0bae858059d35498a51ee217e84e88786e3775cf",
          "md5": "2f3411d3a96e6e0640e6421f0ec7dcb8"
        }
      ]
    }
  ]
}
