{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7.aar",
          "url": "oboemusicplayerandrecorder-0.2.7.aar",
          "size": 1673578,
          "sha512": "eb34a2c9ad85691f3b5fe5f5a09b372e56904a79e6e95a0d57197594875c67985bfb14174ebe96c01da6182d08be295bddd08adc83e057048a5ff10cfd213392",
          "sha256": "36d02f2515ce8e79dc09c5c369312202936e6edbf19cf2f17ee4d988819bcb1b",
          "sha1": "833d2d8f4c143de16cb257ff75ee4619469f1dbd",
          "md5": "32a922ab52b4c3aec3008c0739878e80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7.aar",
          "url": "oboemusicplayerandrecorder-0.2.7.aar",
          "size": 1673578,
          "sha512": "eb34a2c9ad85691f3b5fe5f5a09b372e56904a79e6e95a0d57197594875c67985bfb14174ebe96c01da6182d08be295bddd08adc83e057048a5ff10cfd213392",
          "sha256": "36d02f2515ce8e79dc09c5c369312202936e6edbf19cf2f17ee4d988819bcb1b",
          "sha1": "833d2d8f4c143de16cb257ff75ee4619469f1dbd",
          "md5": "32a922ab52b4c3aec3008c0739878e80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.7-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
