{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboenativemodule",
    "version": "1.0.7-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "oboenativemodule-1.0.7-test.aar",
          "url": "oboenativemodule-1.0.7-test.aar",
          "size": 1375101,
          "sha512": "2fe3de304031c8c5c8007f7f1c1cc69133edbf02ba73d9ac35bb451ec417fd01d72c968ca39236e5f746017169ee71554f7f49f010f2471a180ac62f36415bdb",
          "sha256": "5ccf0b06544ef8aec55da9b56975b0e0b4da271e88548aa601bc5c2975834876",
          "sha1": "337079eedcf5135e57e0663c5fe6dc9ef29bd381",
          "md5": "bad710605b42445f01fc05aeba588ca2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.0.7-test.aar",
          "url": "oboenativemodule-1.0.7-test.aar",
          "size": 1375101,
          "sha512": "2fe3de304031c8c5c8007f7f1c1cc69133edbf02ba73d9ac35bb451ec417fd01d72c968ca39236e5f746017169ee71554f7f49f010f2471a180ac62f36415bdb",
          "sha256": "5ccf0b06544ef8aec55da9b56975b0e0b4da271e88548aa601bc5c2975834876",
          "sha1": "337079eedcf5135e57e0663c5fe6dc9ef29bd381",
          "md5": "bad710605b42445f01fc05aeba588ca2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.0.7-test-sources.jar",
          "url": "oboenativemodule-1.0.7-test-sources.jar",
          "size": 2722,
          "sha512": "7b469088911cd4dbdb891530b3f230ed3e6d63c60a2991a3c8db951fe09f1ebb3a25b89e7d98a41f4e21a75e0f8f79fed4c5ab9c2ceab3c3e22ec145fa018c48",
          "sha256": "da5b3ea193d2f01b3ddc40a025eb7980744245fb7f6caa59ec0a701d79964176",
          "sha1": "2099c6fcfced2d60c5279215633e13324308deeb",
          "md5": "c002ccb70195b6562d350b9da73c7c2e"
        }
      ]
    }
  ]
}
