{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.2.aar",
          "url": "oboemusicplayerandrecorder-0.5.2.aar",
          "size": 1773643,
          "sha512": "93eda24f5b2b572986be580e7e2d94f90920396546a99d1b4a0edef400bde7b622dadd58c1eabae6d76548f1d97f76643bcd131c41a4c9588714e9321865b71f",
          "sha256": "9e9f9f52874b6a1b68dc87d658e4cc7c3aeddeec8f3e8350d9a8db3e612bc87a",
          "sha1": "479bc891a245c5207bd30b5b918af003c8fd76f8",
          "md5": "049cc8d92ddbe28485dfc3f7bc3afd83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.2.aar",
          "url": "oboemusicplayerandrecorder-0.5.2.aar",
          "size": 1773643,
          "sha512": "93eda24f5b2b572986be580e7e2d94f90920396546a99d1b4a0edef400bde7b622dadd58c1eabae6d76548f1d97f76643bcd131c41a4c9588714e9321865b71f",
          "sha256": "9e9f9f52874b6a1b68dc87d658e4cc7c3aeddeec8f3e8350d9a8db3e612bc87a",
          "sha1": "479bc891a245c5207bd30b5b918af003c8fd76f8",
          "md5": "049cc8d92ddbe28485dfc3f7bc3afd83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.2-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.2-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
