{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.1.aar",
          "url": "oboemusicplayerandrecorder-0.3.1.aar",
          "size": 1683912,
          "sha512": "fe47657eb9e21f3ec3596945b5937bc391fc2b470600f54b2f1771c0ad28e833928589fb99c261520eafaf4cd50cf78c98238992ac5a206540d5d170008c5656",
          "sha256": "9760a6a3a5398822d4aec9baa0e9ae091563fe194df7607f70010a4e3c5245b8",
          "sha1": "1585a3e871bb786659bdf3d6927e2876cdd1fc9f",
          "md5": "62165b7b47cda87f2fd82f69625c3f5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.1.aar",
          "url": "oboemusicplayerandrecorder-0.3.1.aar",
          "size": 1683912,
          "sha512": "fe47657eb9e21f3ec3596945b5937bc391fc2b470600f54b2f1771c0ad28e833928589fb99c261520eafaf4cd50cf78c98238992ac5a206540d5d170008c5656",
          "sha256": "9760a6a3a5398822d4aec9baa0e9ae091563fe194df7607f70010a4e3c5245b8",
          "sha1": "1585a3e871bb786659bdf3d6927e2876cdd1fc9f",
          "md5": "62165b7b47cda87f2fd82f69625c3f5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.1-sources.jar",
          "size": 8362,
          "sha512": "a4b13b3a340f12fa41eeed4db98eac70d563c2e95dde6c79817fc6c4cce12bbbee666398a26702a237fbb048dba4d30dd626ee029cdf628c64c60702d0d762df",
          "sha256": "4b70016e484d82ea952e209b0575c1550d10c2e65b3601ee8959af827d8113aa",
          "sha1": "2c514897fffca07b4dbb88df3afb6eac86842f46",
          "md5": "0083477354a7bc7f7f780fddf0e64d91"
        }
      ]
    }
  ]
}
