{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.4.aar",
          "url": "oboemusicplayerandrecorder-0.8.4.aar",
          "size": 2322664,
          "sha512": "4b23f81fd81951538fcb3fc193730646a230a56374061744776843f720fd51077099b87f533c5aaa2bf3c68578dadbf80e4daea69155dc76eb02d17025342c46",
          "sha256": "df85587a987fd7452f822db42dc8775262835c79819b672732a5fada981c72bc",
          "sha1": "9e1a15305f6327f3455a8abc3c735cd017ade315",
          "md5": "133a02af28f029cb0fbf7b998352aeae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.4.aar",
          "url": "oboemusicplayerandrecorder-0.8.4.aar",
          "size": 2322664,
          "sha512": "4b23f81fd81951538fcb3fc193730646a230a56374061744776843f720fd51077099b87f533c5aaa2bf3c68578dadbf80e4daea69155dc76eb02d17025342c46",
          "sha256": "df85587a987fd7452f822db42dc8775262835c79819b672732a5fada981c72bc",
          "sha1": "9e1a15305f6327f3455a8abc3c735cd017ade315",
          "md5": "133a02af28f029cb0fbf7b998352aeae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.4-sources.jar",
          "url": "oboemusicplayerandrecorder-0.8.4-sources.jar",
          "size": 25250,
          "sha512": "0567f5f8407f7feb34d05fcedd5c359a4cc15cbab80bb216aaf9fe810db2a3a84b3e9c0e96bc3b845dba3b9d7f2cfdfb50d0c1485b3b2f3a10b384d29dc09d80",
          "sha256": "db63f13a661665659a29bedd86d78c96e6f51679a6282436a475bf11253a37ae",
          "sha1": "0bae858059d35498a51ee217e84e88786e3775cf",
          "md5": "2f3411d3a96e6e0640e6421f0ec7dcb8"
        }
      ]
    }
  ]
}
