{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.0.aar",
          "url": "oboemusicplayerandrecorder-0.4.0.aar",
          "size": 1737768,
          "sha512": "a685d039eebc24b6a6d4a7cf24e4b1c3f4e421279f7ce1cef90a9d22a6a8c2265b1ee5f88eb596863f3e21b7ce7faa714057436b00495bf64ab855464235d2fd",
          "sha256": "430924bba4e8609ea5d47943845f0ce1cbd5e78c1b17d41164b08f840587f7c7",
          "sha1": "f0ed64f25063c58b2ff6c8005ab35562e4729c43",
          "md5": "dd697cb165dd6981683d6531dbc0fe67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.0.aar",
          "url": "oboemusicplayerandrecorder-0.4.0.aar",
          "size": 1737768,
          "sha512": "a685d039eebc24b6a6d4a7cf24e4b1c3f4e421279f7ce1cef90a9d22a6a8c2265b1ee5f88eb596863f3e21b7ce7faa714057436b00495bf64ab855464235d2fd",
          "sha256": "430924bba4e8609ea5d47943845f0ce1cbd5e78c1b17d41164b08f840587f7c7",
          "sha1": "f0ed64f25063c58b2ff6c8005ab35562e4729c43",
          "md5": "dd697cb165dd6981683d6531dbc0fe67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.0-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.0-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
