{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.7-exp3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7-exp3.aar",
          "url": "oboemusicplayerandrecorder-0.2.7-exp3.aar",
          "size": 1679136,
          "sha512": "f19f4da90889fd4179a491758a4f4bfc741d017f11eafa1ce7a35214b2d5aecf083dc6c5b1a72a1e8be9a99017da78bd81275e780578fcb86ebd085abc022d6e",
          "sha256": "35668e40a58ce10b642882ba514d7aa400a6eab86acda1acac60fc3f3b450812",
          "sha1": "53bd2637e547030bc07c144ef6e76ce6617e9aab",
          "md5": "c4377779490dd9b08c4d1b57e03e954c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7-exp3.aar",
          "url": "oboemusicplayerandrecorder-0.2.7-exp3.aar",
          "size": 1679136,
          "sha512": "f19f4da90889fd4179a491758a4f4bfc741d017f11eafa1ce7a35214b2d5aecf083dc6c5b1a72a1e8be9a99017da78bd81275e780578fcb86ebd085abc022d6e",
          "sha256": "35668e40a58ce10b642882ba514d7aa400a6eab86acda1acac60fc3f3b450812",
          "sha1": "53bd2637e547030bc07c144ef6e76ce6617e9aab",
          "md5": "c4377779490dd9b08c4d1b57e03e954c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7-exp3-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.7-exp3-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
