{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.5-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-3.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-3.aar",
          "size": 1795755,
          "sha512": "84758bb14b0f981a16de01cb526e9a04f2e611fa9570364bc0aed9307eaeec51ef39a2a77d38ddf3f240ab2b6b51ff89f4cbe4dfc1c54c95e5b24eee777262bf",
          "sha256": "44067294582a468e63ad0a7255b87c7d8c4fef41080adcff52b306dd03500c58",
          "sha1": "cdb11dde1b1305c818a109ff1da202c0553669eb",
          "md5": "0576f2e3e4365340a0e9ef72131bae88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-3.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-3.aar",
          "size": 1795755,
          "sha512": "84758bb14b0f981a16de01cb526e9a04f2e611fa9570364bc0aed9307eaeec51ef39a2a77d38ddf3f240ab2b6b51ff89f4cbe4dfc1c54c95e5b24eee777262bf",
          "sha256": "44067294582a468e63ad0a7255b87c7d8c4fef41080adcff52b306dd03500c58",
          "sha1": "cdb11dde1b1305c818a109ff1da202c0553669eb",
          "md5": "0576f2e3e4365340a0e9ef72131bae88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-3-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.5-3-sources.jar",
          "size": 11885,
          "sha512": "4747e99b085df38e9ac8f9b72397dac2036214b4d63d7d02f097af443349954b7dceea28321cbd8740aa5377c0c2c79943c7adbb0a029249f74f648b864f8cc5",
          "sha256": "ee654daf5e4d467dd024782590abd354506b83d1e44855eb9d6e87ebb161da8c",
          "sha1": "612ef51e69b69f13e574da93feff528579ffa6de",
          "md5": "08d071c7161cbefeb27af461cfd0d886"
        }
      ]
    }
  ]
}
