{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.2-exp3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp3.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp3.aar",
          "size": 1739937,
          "sha512": "01b79efd1ce0bc2a6acc896303984282f5f533babaaf96af667aa1605709ea5af59270be0a06c8979f6e96661645e44738fdd585705bf009087002845ef69a38",
          "sha256": "ac639d68e6a23c71db53d0d32b4626e0c1eb2e709e2ba6b2fb490b439b2d7997",
          "sha1": "814a4da08ff0f0c1be7c56369e3819e7963a4ad7",
          "md5": "0190b36a51b494ae76f9dbaca89ab97a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp3.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp3.aar",
          "size": 1739937,
          "sha512": "01b79efd1ce0bc2a6acc896303984282f5f533babaaf96af667aa1605709ea5af59270be0a06c8979f6e96661645e44738fdd585705bf009087002845ef69a38",
          "sha256": "ac639d68e6a23c71db53d0d32b4626e0c1eb2e709e2ba6b2fb490b439b2d7997",
          "sha1": "814a4da08ff0f0c1be7c56369e3819e7963a4ad7",
          "md5": "0190b36a51b494ae76f9dbaca89ab97a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp3-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp3-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
