{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboenativemodule",
    "version": "1.1.4-exp9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp9.aar",
          "url": "oboenativemodule-1.1.4-exp9.aar",
          "size": 1385424,
          "sha512": "3009f778b5423992f5737d70dbf2759c63b5eca9ff54a0ffa20b5603ec17f3765a3350068774e60c1849b3e5c8e8831a29c42f30c717d8bc7f81f7bfdd59b10f",
          "sha256": "0970f6b9e4ee7c217fffcf567291ad1ca16214c9659cdf4bb0b43e3bb23a8daa",
          "sha1": "e38092728e4f120382638c9c0f3b424a186d04be",
          "md5": "b555e2d90afc4f985154fbc282a748c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp9.aar",
          "url": "oboenativemodule-1.1.4-exp9.aar",
          "size": 1385424,
          "sha512": "3009f778b5423992f5737d70dbf2759c63b5eca9ff54a0ffa20b5603ec17f3765a3350068774e60c1849b3e5c8e8831a29c42f30c717d8bc7f81f7bfdd59b10f",
          "sha256": "0970f6b9e4ee7c217fffcf567291ad1ca16214c9659cdf4bb0b43e3bb23a8daa",
          "sha1": "e38092728e4f120382638c9c0f3b424a186d04be",
          "md5": "b555e2d90afc4f985154fbc282a748c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp9-sources.jar",
          "url": "oboenativemodule-1.1.4-exp9-sources.jar",
          "size": 2793,
          "sha512": "0009b3074adcba4ea7aaa5d40d81b02d1c92dd55d2ee2021726fc393307127f03e1855aec8ec4dcb541d8237c9c2b8f99406d4ce050e27a22f8c8c19bea732ae",
          "sha256": "d8bc0619859c0810ebbf9a3a6bb5e8183f402991c5487bc56c914b01c41b0ef7",
          "sha1": "b6e53ca54d0bccb6d284d6c6d17a24cacb22c56b",
          "md5": "03cde79f7b1206f3969086e351a071ce"
        }
      ]
    }
  ]
}
