{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp9.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp9.aar",
          "size": 1714856,
          "sha512": "404a9c9c2fe45edcdc974b8bb8274186ae2e050730cf9d332c881d220bd0ea202d6c95d75a59801baaf05d0571047c95a4c7ccd34807c2c2d0bded1976024f03",
          "sha256": "a3f481ee943d08725869c8d69f09c631bfc32cedf18839a53aa0315db9d2bc2a",
          "sha1": "7c8af726b36dc0a1b6cf61d9dd873d85f8842432",
          "md5": "1f134724400fb143fe1376aeee348af0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp9.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp9.aar",
          "size": 1714856,
          "sha512": "404a9c9c2fe45edcdc974b8bb8274186ae2e050730cf9d332c881d220bd0ea202d6c95d75a59801baaf05d0571047c95a4c7ccd34807c2c2d0bded1976024f03",
          "sha256": "a3f481ee943d08725869c8d69f09c631bfc32cedf18839a53aa0315db9d2bc2a",
          "sha1": "7c8af726b36dc0a1b6cf61d9dd873d85f8842432",
          "md5": "1f134724400fb143fe1376aeee348af0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp9-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp9-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
