{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.1.aar",
          "url": "oboemusicplayerandrecorder-0.2.1.aar",
          "size": 1654007,
          "sha512": "b78126def3fef1b2d9677a500dfa53113f260af4bb4f109dcfde2f44ba5e72c6a9d47a0a0f06f623f8e0f870d3cd70c2e3cfc24b32a5eabad94e2befffcae42e",
          "sha256": "ba3463e6b123c20f84167312dc16df4c77cbee61b5eb2a25490cfffe1396c731",
          "sha1": "01ce5fa68f6059d7ba28eacdd44f1ea2913bbb4a",
          "md5": "057b47c3c500e4b80ab6486b5e936736"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.1.aar",
          "url": "oboemusicplayerandrecorder-0.2.1.aar",
          "size": 1654007,
          "sha512": "b78126def3fef1b2d9677a500dfa53113f260af4bb4f109dcfde2f44ba5e72c6a9d47a0a0f06f623f8e0f870d3cd70c2e3cfc24b32a5eabad94e2befffcae42e",
          "sha256": "ba3463e6b123c20f84167312dc16df4c77cbee61b5eb2a25490cfffe1396c731",
          "sha1": "01ce5fa68f6059d7ba28eacdd44f1ea2913bbb4a",
          "md5": "057b47c3c500e4b80ab6486b5e936736"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.1-sources.jar",
          "size": 8066,
          "sha512": "e466a7abdbbb373c9d81594d7852470acb6444066c22906a91150752bc98b058682bc35b7e410678ca4eee1503edf683edf747d09ef6c945eab4d25bb5bd87f9",
          "sha256": "d9b49f97d66f9fa60b9129633d7ede84459016cc7b362ad02bd0974b7d37cd59",
          "sha1": "bf90dbb4862b6686d313cf7abca548a54cb23c51",
          "md5": "a161f9c6417ee3f7041730e2dbf47610"
        }
      ]
    }
  ]
}
