{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.2-exp5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp5.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp5.aar",
          "size": 1766035,
          "sha512": "1879519d07ff7b1f7828f086f66c8a9954ab44efb7169a0d88aa5c57f1557c8a766a3b2a68d34524e62102f884c5228a72af1d531a7dae27658a53ada08b83ac",
          "sha256": "a156f6fc9cb69bffafe38541c806799ebf9245db944db431d84a57e7c6a3f30c",
          "sha1": "add6b4aee2cb79355c9fcd3c21eb148e811e74dd",
          "md5": "a0813446d57d9ecf4f4197bb5e09eac4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp5.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp5.aar",
          "size": 1766035,
          "sha512": "1879519d07ff7b1f7828f086f66c8a9954ab44efb7169a0d88aa5c57f1557c8a766a3b2a68d34524e62102f884c5228a72af1d531a7dae27658a53ada08b83ac",
          "sha256": "a156f6fc9cb69bffafe38541c806799ebf9245db944db431d84a57e7c6a3f30c",
          "sha1": "add6b4aee2cb79355c9fcd3c21eb148e811e74dd",
          "md5": "a0813446d57d9ecf4f4197bb5e09eac4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp5-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp5-sources.jar",
          "size": 11247,
          "sha512": "16aa816706f4c0d185bfe7bc1bb239f0ea5a535f34435ef0896e14a5171a19348cdf6f3dfd9ca314ee9692844a41d3a2102ae3076d9daba61726d6c01de8953d",
          "sha256": "fdb2ffa8ad1c5750c1f0bc3eeb3d80b93b6c9af53174bb14bc2c9568d7f31bfa",
          "sha1": "cda2df24009dcfc7c13f84eb4aab672c3fa1f12a",
          "md5": "318db1e00241502f5c1919b0606270c8"
        }
      ]
    }
  ]
}
