{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-1.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-1.aar",
          "size": 1719842,
          "sha512": "79c0b80fb7de0e59f90f2bf11a24033f40fbc7f76af0020ea5e1a99737fef2b890af5d0c3590cd839ae02035c6ebdb3455a73190f7940e90b42993e3ed2b65d1",
          "sha256": "6aa43e7b2774fc129c794045841cc99ffbfad2c227dcd8b2803d3110f76acb12",
          "sha1": "81d101c95744a00a83ac9fa71ce8dddd3f959849",
          "md5": "c26dd2e100502568c0e6710a76936b3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-1.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-1.aar",
          "size": 1719842,
          "sha512": "79c0b80fb7de0e59f90f2bf11a24033f40fbc7f76af0020ea5e1a99737fef2b890af5d0c3590cd839ae02035c6ebdb3455a73190f7940e90b42993e3ed2b65d1",
          "sha256": "6aa43e7b2774fc129c794045841cc99ffbfad2c227dcd8b2803d3110f76acb12",
          "sha1": "81d101c95744a00a83ac9fa71ce8dddd3f959849",
          "md5": "c26dd2e100502568c0e6710a76936b3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-1-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
