{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.5-exp1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp1.aar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp1.aar",
          "size": 1662679,
          "sha512": "dc3af491136cf3133533a9fcc6b2c84a31137718fbd23d0f08c8f4d16a99476f12d081bc7222adf6972cc9f4f43ee0ca8c6882b7b4a903fa9f8cfc775d5177fd",
          "sha256": "f636bd84b0589b038f52371018f2995205c4c8f98bc70da648ed0da6f39c3073",
          "sha1": "6b4220cf9c1bfdf815ba65c12c869ff54365b5ba",
          "md5": "22278f06bc1432d368e4db05d5262fa3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp1.aar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp1.aar",
          "size": 1662679,
          "sha512": "dc3af491136cf3133533a9fcc6b2c84a31137718fbd23d0f08c8f4d16a99476f12d081bc7222adf6972cc9f4f43ee0ca8c6882b7b4a903fa9f8cfc775d5177fd",
          "sha256": "f636bd84b0589b038f52371018f2995205c4c8f98bc70da648ed0da6f39c3073",
          "sha1": "6b4220cf9c1bfdf815ba65c12c869ff54365b5ba",
          "md5": "22278f06bc1432d368e4db05d5262fa3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp1-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
