{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp15.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp15.aar",
          "size": 2522819,
          "sha512": "ed9e7f557e65cac9f7557d5f95ede142294c31abe671ed6539a5662f8a655ccc29c14b1af80a27fa03e1509cc18bda8036fc37ddf0f7003f34e51357bba6b709",
          "sha256": "9a939900b9a3d4e75ad1ca50ca3e074b4a67c285f8b41af7ddc05fcd25810f3d",
          "sha1": "6213e384194b6eb43aeb425e7d0df74072cf790a",
          "md5": "ced93927844f36e988305e97f755eeb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp15.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp15.aar",
          "size": 2522819,
          "sha512": "ed9e7f557e65cac9f7557d5f95ede142294c31abe671ed6539a5662f8a655ccc29c14b1af80a27fa03e1509cc18bda8036fc37ddf0f7003f34e51357bba6b709",
          "sha256": "9a939900b9a3d4e75ad1ca50ca3e074b4a67c285f8b41af7ddc05fcd25810f3d",
          "sha1": "6213e384194b6eb43aeb425e7d0df74072cf790a",
          "md5": "ced93927844f36e988305e97f755eeb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp15-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp15-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
