{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.7.6.aar",
          "url": "oboemusicplayerandrecorder-0.7.6.aar",
          "size": 2060404,
          "sha512": "3e3fee05d9cb9c23b485eb5a3b78c2872b6db2122d1089f92ee8beb93eed62648aaca372a755a61ed476fd19d21874802cdc13817e80e1bd0d540949803ee920",
          "sha256": "316ceb5a479719543993aa03b2d53c0160b68a9b9a4305c3cfbb43bca0f1b0ad",
          "sha1": "0faeb6e901c197345e3681b70d97e6ab740af5aa",
          "md5": "b6ca94d21cce869cf3baa4e8abc07097"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.7.6.aar",
          "url": "oboemusicplayerandrecorder-0.7.6.aar",
          "size": 2060404,
          "sha512": "3e3fee05d9cb9c23b485eb5a3b78c2872b6db2122d1089f92ee8beb93eed62648aaca372a755a61ed476fd19d21874802cdc13817e80e1bd0d540949803ee920",
          "sha256": "316ceb5a479719543993aa03b2d53c0160b68a9b9a4305c3cfbb43bca0f1b0ad",
          "sha1": "0faeb6e901c197345e3681b70d97e6ab740af5aa",
          "md5": "b6ca94d21cce869cf3baa4e8abc07097"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.7.6-sources.jar",
          "url": "oboemusicplayerandrecorder-0.7.6-sources.jar",
          "size": 11621,
          "sha512": "ff2d531d23d2d15b066d108fb2ecb9fb3125ad1862e4befee079c26d61da02c32fea81af55534e9b83c1dcd9015054e2d39915490b5b374fe6b47dd8fb5d0099",
          "sha256": "3f1a74c2ef6d87aae220de103661601c80e7b549ee0faf3f0d850159caf6692f",
          "sha1": "07bcba14eb56baf6dd063589b4c4bd86985496be",
          "md5": "dfed5cafbeec7bad9bcbc640f2b8d65a"
        }
      ]
    }
  ]
}
