{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.1-exp11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp11.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp11.aar",
          "size": 1772612,
          "sha512": "c41bd5a705beadc5e4f85f13b304668f03b366cb750d74938e0eb38714d3b0a883ce566de5af42304c95a2020f2ab5040c9857e052911a82d22b2e469614d3f2",
          "sha256": "05d5fb4e7dc1b01b66dad1fde9f8159434abba5cfb3d27a625d7576c97a4b865",
          "sha1": "7a893dd142ffddc301d32bb48d9d6eff1ef9459b",
          "md5": "1f78f22d9484cce0aa1c273fb1819c1e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp11.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp11.aar",
          "size": 1772612,
          "sha512": "c41bd5a705beadc5e4f85f13b304668f03b366cb750d74938e0eb38714d3b0a883ce566de5af42304c95a2020f2ab5040c9857e052911a82d22b2e469614d3f2",
          "sha256": "05d5fb4e7dc1b01b66dad1fde9f8159434abba5cfb3d27a625d7576c97a4b865",
          "sha1": "7a893dd142ffddc301d32bb48d9d6eff1ef9459b",
          "md5": "1f78f22d9484cce0aa1c273fb1819c1e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp11-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp11-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
