{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.8.aar",
          "url": "oboemusicplayerandrecorder-0.2.8.aar",
          "size": 1676393,
          "sha512": "07abf29aef72c567abbc67a22f55ae21ab423a1009b0a2d7b5aa7e1f15349683a7b09b5f4ecd03b706bf43380213482477106fec674488fd423ab789ac912b7c",
          "sha256": "3f983cd992586138f13665319bd384200531d09ed090319ccd63c0d8b9ef60a9",
          "sha1": "ba1234ae76d8693625e8b262f1299c09d7387f53",
          "md5": "9ecbce5ec6fa898c0181b296440c50e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.8.aar",
          "url": "oboemusicplayerandrecorder-0.2.8.aar",
          "size": 1676393,
          "sha512": "07abf29aef72c567abbc67a22f55ae21ab423a1009b0a2d7b5aa7e1f15349683a7b09b5f4ecd03b706bf43380213482477106fec674488fd423ab789ac912b7c",
          "sha256": "3f983cd992586138f13665319bd384200531d09ed090319ccd63c0d8b9ef60a9",
          "sha1": "ba1234ae76d8693625e8b262f1299c09d7387f53",
          "md5": "9ecbce5ec6fa898c0181b296440c50e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.8-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.8-sources.jar",
          "size": 7141,
          "sha512": "f41bb29276cd248694ae3da3b57110b6260297874a8d0e089ea3a88fdfee43ab1f2534bb574d267cb695a6e172f7843d7a0357b4cbc02ceb4e132393a7a31df4",
          "sha256": "230bcc1b87ad33eaf9740ad0584a33048f49c029d289ef3e6c7b59cc89574760",
          "sha1": "23d3c6893115aa340ef69843bbdca4e03f2e69e2",
          "md5": "5109f12a00a732af2cb133a6ac5387a1"
        }
      ]
    }
  ]
}
