{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.1.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.13.aar",
          "url": "oboemusicplayerandrecorder-0.1.13.aar",
          "size": 1397352,
          "sha512": "a66fcc0070a28abccb7f408aeb36a73b63d4057f83008f67766537e4ec547a3feef1d9222b7237b6dc86b3d7d7c9037b16002e3f881b0c4e19e1008acd2a8f36",
          "sha256": "1318d8e4aecceb3c715b399425dc63adbd5706d959f420db8eb21db91f215c4d",
          "sha1": "9fd32ca7971c422817cfa2f393e9aed2fb714a1f",
          "md5": "c3b1001f33fffa60dc86dbd51a6e4dd8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.13.aar",
          "url": "oboemusicplayerandrecorder-0.1.13.aar",
          "size": 1397352,
          "sha512": "a66fcc0070a28abccb7f408aeb36a73b63d4057f83008f67766537e4ec547a3feef1d9222b7237b6dc86b3d7d7c9037b16002e3f881b0c4e19e1008acd2a8f36",
          "sha256": "1318d8e4aecceb3c715b399425dc63adbd5706d959f420db8eb21db91f215c4d",
          "sha1": "9fd32ca7971c422817cfa2f393e9aed2fb714a1f",
          "md5": "c3b1001f33fffa60dc86dbd51a6e4dd8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.13-sources.jar",
          "url": "oboemusicplayerandrecorder-0.1.13-sources.jar",
          "size": 3836,
          "sha512": "9bb317eaa17184b09b2363108c65f7b02d6ec1f702c34e9e7501ae074e3f7047628aefd3cc2a64d8a7b3e9929e73a881e1da4ecddf365ba5b4911a4a3b85bfa3",
          "sha256": "1ee21c8ee610282df060bf3b2c5ec4057cfd51f9795337e0b1aa882e9362d6ef",
          "sha1": "ea902a54009895c91b1d37da4d15992913318c98",
          "md5": "bba36038ff5dd29227a74b644c3e3d26"
        }
      ]
    }
  ]
}
