{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.7.5.aar",
          "url": "oboemusicplayerandrecorder-0.7.5.aar",
          "size": 2059082,
          "sha512": "af1ec6d86edac26fbb54d9f847e4f1e7a8b3f78c443156e6e39c6d53395ca2b75640122717e3daad6d7650437252c780362fc4bda586961de5a08f56933323af",
          "sha256": "438765356677ec9dcd4b90c9414300a17212896aeb4e8d3f960616a959f75409",
          "sha1": "ba24ae9034586e6f038d502499b1d41ccc84b7a4",
          "md5": "731c3280f8584889088eadf72e354333"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.7.5.aar",
          "url": "oboemusicplayerandrecorder-0.7.5.aar",
          "size": 2059082,
          "sha512": "af1ec6d86edac26fbb54d9f847e4f1e7a8b3f78c443156e6e39c6d53395ca2b75640122717e3daad6d7650437252c780362fc4bda586961de5a08f56933323af",
          "sha256": "438765356677ec9dcd4b90c9414300a17212896aeb4e8d3f960616a959f75409",
          "sha1": "ba24ae9034586e6f038d502499b1d41ccc84b7a4",
          "md5": "731c3280f8584889088eadf72e354333"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.7.5-sources.jar",
          "url": "oboemusicplayerandrecorder-0.7.5-sources.jar",
          "size": 11599,
          "sha512": "3caa8502b0473fa2f77f8bf38c7830659f9040e1bfdacc1083c4c3e21936bab9621a530b7cda198bc2ffab384b2edd3abcc930cfa358b4dbf322433cde213b7e",
          "sha256": "dfd154ead07c1758cce6694da60fbe7e48b2f487b74601ac5a60dfec04fe92a6",
          "sha1": "ad752599b87d0944e292525798a8500dc828b004",
          "md5": "8ca39cd2b10d85e86ef0a880338b6307"
        }
      ]
    }
  ]
}
