{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.1-exp2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp2.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp2.aar",
          "size": 1774144,
          "sha512": "a8f80884a22a844ed842fbb3d162f571effbbe7a9df267e967b77e209730aa754b4271f23113b74be6be624089ab5f998047b1d122c127d3d39dafca0a495116",
          "sha256": "156d85de8bd56d0ae500f3994722c5b655f4af4f243b409b8d94fbcc200c29fa",
          "sha1": "7f6b277a9ec6a325f69b1b2bc02fdad7aad78af3",
          "md5": "5d6118e499280a05ba47f926d42845c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp2.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp2.aar",
          "size": 1774144,
          "sha512": "a8f80884a22a844ed842fbb3d162f571effbbe7a9df267e967b77e209730aa754b4271f23113b74be6be624089ab5f998047b1d122c127d3d39dafca0a495116",
          "sha256": "156d85de8bd56d0ae500f3994722c5b655f4af4f243b409b8d94fbcc200c29fa",
          "sha1": "7f6b277a9ec6a325f69b1b2bc02fdad7aad78af3",
          "md5": "5d6118e499280a05ba47f926d42845c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp2-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp2-sources.jar",
          "size": 14648,
          "sha512": "52e99f5d0f1e48ba575c965d2a92b1a84cd57223ee6450a8cd47a976d28f8710cafa7d9ea11275f80bf0bf684ab4ea7a711c1e76f100080264a2d32e206f5c1f",
          "sha256": "6e15391f5838685caff0391aa1aa17bb662ef3dc7ba2fee6ba60d948ecb55df4",
          "sha1": "1212f38fe6f3210ef343ccef8498cb14befc8a0a",
          "md5": "56471c26a905683ad23f0c198fe8f7dc"
        }
      ]
    }
  ]
}
