{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp17.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp17.aar",
          "size": 2522697,
          "sha512": "d5a909baa9c56413001b65720516bf35d046d23c684fe87b12d40071636a38f86999217ae0a9c714f3bb90f4919a8d93b27f8ecb8c99c1af91b98cb2b7a5ce13",
          "sha256": "11478f6890ebf621a88426eb9cb7ee4b0c8b8351ae458a5d67d7f7d0c5627a7a",
          "sha1": "187f88cc026ce160ac5136361f2aac96904941d3",
          "md5": "fef614907d816a0380bcd84354a95d3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp17.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp17.aar",
          "size": 2522697,
          "sha512": "d5a909baa9c56413001b65720516bf35d046d23c684fe87b12d40071636a38f86999217ae0a9c714f3bb90f4919a8d93b27f8ecb8c99c1af91b98cb2b7a5ce13",
          "sha256": "11478f6890ebf621a88426eb9cb7ee4b0c8b8351ae458a5d67d7f7d0c5627a7a",
          "sha1": "187f88cc026ce160ac5136361f2aac96904941d3",
          "md5": "fef614907d816a0380bcd84354a95d3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp17-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp17-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
