{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.9.aar",
          "url": "oboemusicplayerandrecorder-0.6.9.aar",
          "size": 1880307,
          "sha512": "eb6c3737fa7c6911b31cf6fc0207070553f1645fd9a1fd1fb0e591920797ee56c67107ca21c418d99264320882dac45addb4a1825df79175ec3c3d66feb88465",
          "sha256": "f73040e7257d7f0c9e2ed485c0505d0c67f1a95947564f6b269e3c1c100b57af",
          "sha1": "f18637ed1a6ff81fb698d7a75507adfb1dcd0c41",
          "md5": "0b48389d7cef1fa63a2ae95d17f24942"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.9.aar",
          "url": "oboemusicplayerandrecorder-0.6.9.aar",
          "size": 1880307,
          "sha512": "eb6c3737fa7c6911b31cf6fc0207070553f1645fd9a1fd1fb0e591920797ee56c67107ca21c418d99264320882dac45addb4a1825df79175ec3c3d66feb88465",
          "sha256": "f73040e7257d7f0c9e2ed485c0505d0c67f1a95947564f6b269e3c1c100b57af",
          "sha1": "f18637ed1a6ff81fb698d7a75507adfb1dcd0c41",
          "md5": "0b48389d7cef1fa63a2ae95d17f24942"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.9-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.9-sources.jar",
          "size": 11348,
          "sha512": "e9d315cf5f89a3e4d5d9646cba0adebd32243c31d735c0ec0585408c1f8939017c7f11e6b87977f653e303db12b5419d701d44a44d86a7da5ccf89f694f3debe",
          "sha256": "d80b567591ac2fa0f3c76296d68cb7b74bc83d5acd3155d9bc60b5a8cedc1925",
          "sha1": "83fb3ff53c5afcca85ed969a55d8c211bcba5250",
          "md5": "6281214c1a04e03a2f88ba9d1c795df2"
        }
      ]
    }
  ]
}
