{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.14.aar",
          "url": "oboemusicplayerandrecorder-0.1.14.aar",
          "size": 1397280,
          "sha512": "9ba6acb1e66d1e785c429562e77f5ee90adf57b3c1832b760bdc5c20a6bea44b5b49123c4a1d97724d6217de8ec3ddcee12f0ea8f649539ee06361a904f7adc6",
          "sha256": "b2842c2316117b5a976e89a39963749de9307a5022c02261bd7cdabd7fca1d92",
          "sha1": "987518b51f6655b841febe10499ceb4f567ef8b1",
          "md5": "be43175b70aff3765271283e2e644023"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.14.aar",
          "url": "oboemusicplayerandrecorder-0.1.14.aar",
          "size": 1397280,
          "sha512": "9ba6acb1e66d1e785c429562e77f5ee90adf57b3c1832b760bdc5c20a6bea44b5b49123c4a1d97724d6217de8ec3ddcee12f0ea8f649539ee06361a904f7adc6",
          "sha256": "b2842c2316117b5a976e89a39963749de9307a5022c02261bd7cdabd7fca1d92",
          "sha1": "987518b51f6655b841febe10499ceb4f567ef8b1",
          "md5": "be43175b70aff3765271283e2e644023"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.14-sources.jar",
          "url": "oboemusicplayerandrecorder-0.1.14-sources.jar",
          "size": 3836,
          "sha512": "9bb317eaa17184b09b2363108c65f7b02d6ec1f702c34e9e7501ae074e3f7047628aefd3cc2a64d8a7b3e9929e73a881e1da4ecddf365ba5b4911a4a3b85bfa3",
          "sha256": "1ee21c8ee610282df060bf3b2c5ec4057cfd51f9795337e0b1aa882e9362d6ef",
          "sha1": "ea902a54009895c91b1d37da4d15992913318c98",
          "md5": "bba36038ff5dd29227a74b644c3e3d26"
        }
      ]
    }
  ]
}
