{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.5.aar",
          "url": "oboemusicplayerandrecorder-0.1.5.aar",
          "size": 1394814,
          "sha512": "1e2455fcd37ed463729eeadef9224903137c247970394da56bf6ebafb49d972889523656c6fde048379aeb505ee34b73bfdbee1696df9565a25757892cbfeca2",
          "sha256": "47e8fa73b87c096c937e5281ed5b4bd25341924e3f4873bf6320dbfeae11eda7",
          "sha1": "c42d1dfd943e85d2c33566d2424521b9baaaa272",
          "md5": "1d365a7e78cf990954cb29b0e17b9ca4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.5.aar",
          "url": "oboemusicplayerandrecorder-0.1.5.aar",
          "size": 1394814,
          "sha512": "1e2455fcd37ed463729eeadef9224903137c247970394da56bf6ebafb49d972889523656c6fde048379aeb505ee34b73bfdbee1696df9565a25757892cbfeca2",
          "sha256": "47e8fa73b87c096c937e5281ed5b4bd25341924e3f4873bf6320dbfeae11eda7",
          "sha1": "c42d1dfd943e85d2c33566d2424521b9baaaa272",
          "md5": "1d365a7e78cf990954cb29b0e17b9ca4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.5-sources.jar",
          "url": "oboemusicplayerandrecorder-0.1.5-sources.jar",
          "size": 3793,
          "sha512": "c832beb087193d87f6a9eaadd578110cd9b390d7d95f9b35aae55b6b2a71d2e2726fad5aebb65560c8257ff8ad9ef4182919a980ac9b2cd9bd57273447ce9388",
          "sha256": "3c20d5df961017a9b8eb42ead9df3c9cbfb4417621d916b03af597ed3aa5f7d3",
          "sha1": "33a28da687d1bdc3cf5d31460da074b04ca5eaa0",
          "md5": "bbf5f2c643d78b06bbd53854996c5865"
        }
      ]
    }
  ]
}
