{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp6.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp6.aar",
          "size": 1719843,
          "sha512": "be0f7c492cb3163722982f2ee51f84e7445bc5b42bfd70c19eb1e2cf03aa4fc2138e6ee194ebc742a81d76092c6d6bb6248a9431283bd0f4e6e943a4855c0799",
          "sha256": "bb90490962c8d595e3f9ce8237571e15df0679d0ae282c3d9518e00138a1af6a",
          "sha1": "2b60e1b21671b9bf130be6b83dc611c729c97e1f",
          "md5": "9a9460385e9648c88b08ddff449283ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp6.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp6.aar",
          "size": 1719843,
          "sha512": "be0f7c492cb3163722982f2ee51f84e7445bc5b42bfd70c19eb1e2cf03aa4fc2138e6ee194ebc742a81d76092c6d6bb6248a9431283bd0f4e6e943a4855c0799",
          "sha256": "bb90490962c8d595e3f9ce8237571e15df0679d0ae282c3d9518e00138a1af6a",
          "sha1": "2b60e1b21671b9bf130be6b83dc611c729c97e1f",
          "md5": "9a9460385e9648c88b08ddff449283ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp6-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp6-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
