{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp14.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp14.aar",
          "size": 2522111,
          "sha512": "27caed6fa4952735508a1f9cbd128732d1d1a45de200cd8b9a28dd34739e52f63398f224055de8f0a0cabba17e74b7053e32695ad8c6e4af37ebf72bfd7ecb77",
          "sha256": "73f58488a5738cbb05e7be512686f317241604d3eaf807b8e1ea6db115f8b111",
          "sha1": "72bfd9f0f1902bab96802ae2ef8412c48a09ea5e",
          "md5": "16b349cb1806ffef0ecd5e1cf22934cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp14.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp14.aar",
          "size": 2522111,
          "sha512": "27caed6fa4952735508a1f9cbd128732d1d1a45de200cd8b9a28dd34739e52f63398f224055de8f0a0cabba17e74b7053e32695ad8c6e4af37ebf72bfd7ecb77",
          "sha256": "73f58488a5738cbb05e7be512686f317241604d3eaf807b8e1ea6db115f8b111",
          "sha1": "72bfd9f0f1902bab96802ae2ef8412c48a09ea5e",
          "md5": "16b349cb1806ffef0ecd5e1cf22934cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp14-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp14-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
