{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.5.aar",
          "url": "oboemusicplayerandrecorder-0.4.5.aar",
          "size": 1763188,
          "sha512": "8098836ab79b66be8f16f8256cef33f6836620431d80577fda75893ca7437bf5528c4354094b254ee84467855c3e42aa5b8226a3f67948ac0b60b278018e261c",
          "sha256": "4251a7885b87f4f581b9bd2c23e051e5869174afee7b2abb4465cb49dc2d9b6f",
          "sha1": "5dcaeb0da0643f3b122e47c85fa6ae96fe43d579",
          "md5": "8d8b51204b3019a71f67560c6a0f401d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.5.aar",
          "url": "oboemusicplayerandrecorder-0.4.5.aar",
          "size": 1763188,
          "sha512": "8098836ab79b66be8f16f8256cef33f6836620431d80577fda75893ca7437bf5528c4354094b254ee84467855c3e42aa5b8226a3f67948ac0b60b278018e261c",
          "sha256": "4251a7885b87f4f581b9bd2c23e051e5869174afee7b2abb4465cb49dc2d9b6f",
          "sha1": "5dcaeb0da0643f3b122e47c85fa6ae96fe43d579",
          "md5": "8d8b51204b3019a71f67560c6a0f401d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.5-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.5-sources.jar",
          "size": 11248,
          "sha512": "54abe542bbcb2149b6dfcc9fa3db8879ba66d52c34eca30d2710aeadd568c447a996ba53c4f82599a2ce7f95f67f605284cc658b10590fdfd9989b922c4c191d",
          "sha256": "dca2a5b49c2f10eccc31cd143028169fd5d5eddafc5814edbafe0b2feffc2785",
          "sha1": "4bff27bb879ea4051e8c28b4ef3c872fb9aac2ef",
          "md5": "4292b22e7e0eef3430de175ec2186a82"
        }
      ]
    }
  ]
}
