{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.5.aar",
          "url": "oboemusicplayerandrecorder-0.8.5.aar",
          "size": 2331643,
          "sha512": "1c05ae74cc19b9ce451ed4ce39c0a40d0de7bbad1d55cdd28e2850fbd14c928e0ad3e3e876230fb74e5cfa5bacd9c06bb5e5bd5976797b5ee180c550c852f6f0",
          "sha256": "53f4198a8d4cde84381f39106b0875ee75212681799425d10b5ed138d1779f58",
          "sha1": "14247c07e8fb33cb3e9a2dbaac238751a4057b91",
          "md5": "c9518f1f6b2bf48fcddfffd873c0e9a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.5.aar",
          "url": "oboemusicplayerandrecorder-0.8.5.aar",
          "size": 2331643,
          "sha512": "1c05ae74cc19b9ce451ed4ce39c0a40d0de7bbad1d55cdd28e2850fbd14c928e0ad3e3e876230fb74e5cfa5bacd9c06bb5e5bd5976797b5ee180c550c852f6f0",
          "sha256": "53f4198a8d4cde84381f39106b0875ee75212681799425d10b5ed138d1779f58",
          "sha1": "14247c07e8fb33cb3e9a2dbaac238751a4057b91",
          "md5": "c9518f1f6b2bf48fcddfffd873c0e9a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.5-sources.jar",
          "url": "oboemusicplayerandrecorder-0.8.5-sources.jar",
          "size": 25072,
          "sha512": "de2d3e2a07cf73ce10d6fa763a668584528988dc3e131f1849bdcbcf7dff7a0f3fd489e1aacb54bb5305139dbe3745754bb049fba2e112eb2888b880b08e98e2",
          "sha256": "c15075d39be982d9cd462b8861737c904ff77299eee621094f8d9fb32aa9df4a",
          "sha1": "c97611eb6664b4ad4a2afed13b40b9264fdade80",
          "md5": "6816e1353d0a41499c41b4a6f8e59569"
        }
      ]
    }
  ]
}
