{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.12.aar",
          "url": "oboemusicplayerandrecorder-0.6.12.aar",
          "size": 1878952,
          "sha512": "ec5318f41d0e1ff009b1da2475758ff534d8fc2c9e8f4e67296d855fb097e8082b07966d7be8346a4790a6b0ae65c3f66a99a55caaa9f78add0b22d5baf53176",
          "sha256": "b66ffb616c660d5356be14635d2a192bc14d269609952f346e307de00748b27d",
          "sha1": "61e9c6da04d79fbd5b54250642dbc76f1870c65f",
          "md5": "93898cad4fce47f462e559f25a2bc7c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.12.aar",
          "url": "oboemusicplayerandrecorder-0.6.12.aar",
          "size": 1878952,
          "sha512": "ec5318f41d0e1ff009b1da2475758ff534d8fc2c9e8f4e67296d855fb097e8082b07966d7be8346a4790a6b0ae65c3f66a99a55caaa9f78add0b22d5baf53176",
          "sha256": "b66ffb616c660d5356be14635d2a192bc14d269609952f346e307de00748b27d",
          "sha1": "61e9c6da04d79fbd5b54250642dbc76f1870c65f",
          "md5": "93898cad4fce47f462e559f25a2bc7c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.12-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.12-sources.jar",
          "size": 11348,
          "sha512": "e9d315cf5f89a3e4d5d9646cba0adebd32243c31d735c0ec0585408c1f8939017c7f11e6b87977f653e303db12b5419d701d44a44d86a7da5ccf89f694f3debe",
          "sha256": "d80b567591ac2fa0f3c76296d68cb7b74bc83d5acd3155d9bc60b5a8cedc1925",
          "sha1": "83fb3ff53c5afcca85ed969a55d8c211bcba5250",
          "md5": "6281214c1a04e03a2f88ba9d1c795df2"
        }
      ]
    }
  ]
}
