{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.2-exp4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp4.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp4.aar",
          "size": 1765626,
          "sha512": "7fc2275760a0aad192983442d7d69209ead8611e68284888f9e1c9e309cbf64076ba65e4bb09dceafb243a68c3cf689c6f147d87bf3af74ec777968c6c101812",
          "sha256": "9e34de35cebc87ac232a40a1470a26990f8dec04eca7f7c44ddeab30287cd594",
          "sha1": "dfed13b543bbcb3ee726935d30a752c9ba85dcde",
          "md5": "42f4f623f5df78b7c753a3fee2a4396d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp4.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp4.aar",
          "size": 1765626,
          "sha512": "7fc2275760a0aad192983442d7d69209ead8611e68284888f9e1c9e309cbf64076ba65e4bb09dceafb243a68c3cf689c6f147d87bf3af74ec777968c6c101812",
          "sha256": "9e34de35cebc87ac232a40a1470a26990f8dec04eca7f7c44ddeab30287cd594",
          "sha1": "dfed13b543bbcb3ee726935d30a752c9ba85dcde",
          "md5": "42f4f623f5df78b7c753a3fee2a4396d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp4-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp4-sources.jar",
          "size": 11247,
          "sha512": "16aa816706f4c0d185bfe7bc1bb239f0ea5a535f34435ef0896e14a5171a19348cdf6f3dfd9ca314ee9692844a41d3a2102ae3076d9daba61726d6c01de8953d",
          "sha256": "fdb2ffa8ad1c5750c1f0bc3eeb3d80b93b6c9af53174bb14bc2c9568d7f31bfa",
          "sha1": "cda2df24009dcfc7c13f84eb4aab672c3fa1f12a",
          "md5": "318db1e00241502f5c1919b0606270c8"
        }
      ]
    }
  ]
}
