{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.6-11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.6-11.aar",
          "url": "oboemusicplayerandrecorder-0.4.6-11.aar",
          "size": 1765825,
          "sha512": "e1db9aff0344e1e0a9b04a626c240d053e779e36feabc2df4454b4897184cf4c84c9fc27ed7679179e7794ad1b92994aab691d2851aae29205c2cb4add7bb027",
          "sha256": "30e844f61ef06fe4157e2b27154b78a7b538e1c7e94d68a29023320bd0d6df9f",
          "sha1": "c47353dac01a281aaeaee3c23f052908ccc81f22",
          "md5": "e9e1ead13216bd7a808ed7749057453a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.6-11.aar",
          "url": "oboemusicplayerandrecorder-0.4.6-11.aar",
          "size": 1765825,
          "sha512": "e1db9aff0344e1e0a9b04a626c240d053e779e36feabc2df4454b4897184cf4c84c9fc27ed7679179e7794ad1b92994aab691d2851aae29205c2cb4add7bb027",
          "sha256": "30e844f61ef06fe4157e2b27154b78a7b538e1c7e94d68a29023320bd0d6df9f",
          "sha1": "c47353dac01a281aaeaee3c23f052908ccc81f22",
          "md5": "e9e1ead13216bd7a808ed7749057453a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.6-11-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.6-11-sources.jar",
          "size": 11247,
          "sha512": "16aa816706f4c0d185bfe7bc1bb239f0ea5a535f34435ef0896e14a5171a19348cdf6f3dfd9ca314ee9692844a41d3a2102ae3076d9daba61726d6c01de8953d",
          "sha256": "fdb2ffa8ad1c5750c1f0bc3eeb3d80b93b6c9af53174bb14bc2c9568d7f31bfa",
          "sha1": "cda2df24009dcfc7c13f84eb4aab672c3fa1f12a",
          "md5": "318db1e00241502f5c1919b0606270c8"
        }
      ]
    }
  ]
}
