{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.9-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.9-2.aar",
          "url": "oboemusicplayerandrecorder-0.4.9-2.aar",
          "size": 1775865,
          "sha512": "e930ea28905238f06c722b687395483693087dcf1d885f69284ec1c06013caf7b066608310a7f117fbab18e36ce1c3e63ecec92ce8a4e248fcd9f14d9065a4fd",
          "sha256": "0535e1acf2d25514069819ca34e5216fb2873da4edc06d97e5274be975707d50",
          "sha1": "ed21d1a86195bcb5b8d87e25e93ef7a27abbea79",
          "md5": "172d47be56426eb7fe99d8e4b82241b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.9-2.aar",
          "url": "oboemusicplayerandrecorder-0.4.9-2.aar",
          "size": 1775865,
          "sha512": "e930ea28905238f06c722b687395483693087dcf1d885f69284ec1c06013caf7b066608310a7f117fbab18e36ce1c3e63ecec92ce8a4e248fcd9f14d9065a4fd",
          "sha256": "0535e1acf2d25514069819ca34e5216fb2873da4edc06d97e5274be975707d50",
          "sha1": "ed21d1a86195bcb5b8d87e25e93ef7a27abbea79",
          "md5": "172d47be56426eb7fe99d8e4b82241b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.9-2-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.9-2-sources.jar",
          "size": 11247,
          "sha512": "16aa816706f4c0d185bfe7bc1bb239f0ea5a535f34435ef0896e14a5171a19348cdf6f3dfd9ca314ee9692844a41d3a2102ae3076d9daba61726d6c01de8953d",
          "sha256": "fdb2ffa8ad1c5750c1f0bc3eeb3d80b93b6c9af53174bb14bc2c9568d7f31bfa",
          "sha1": "cda2df24009dcfc7c13f84eb4aab672c3fa1f12a",
          "md5": "318db1e00241502f5c1919b0606270c8"
        }
      ]
    }
  ]
}
