{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.4-exp",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.4-exp.aar",
          "url": "oboemusicplayerandrecorder-0.2.4-exp.aar",
          "size": 1663198,
          "sha512": "626e7f49efefdecfec81ef20508ab8066c4ce2a673acc9d07b64d9b641c9dab8b1d147b17d6b4ec9a691c9449caddd3c4c64a9212e2ad31257b33d7981a89ff6",
          "sha256": "6b1102676affca8c9fdfc252f2931ffd75c8f1bf97a524edd154ffe72092ec60",
          "sha1": "4385bda7d6d491ad1c9bd6bff46331f8a701d861",
          "md5": "f22887b6b021bf43d62b5050c01d49ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.4-exp.aar",
          "url": "oboemusicplayerandrecorder-0.2.4-exp.aar",
          "size": 1663198,
          "sha512": "626e7f49efefdecfec81ef20508ab8066c4ce2a673acc9d07b64d9b641c9dab8b1d147b17d6b4ec9a691c9449caddd3c4c64a9212e2ad31257b33d7981a89ff6",
          "sha256": "6b1102676affca8c9fdfc252f2931ffd75c8f1bf97a524edd154ffe72092ec60",
          "sha1": "4385bda7d6d491ad1c9bd6bff46331f8a701d861",
          "md5": "f22887b6b021bf43d62b5050c01d49ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.4-exp-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.4-exp-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
