{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4.aar",
          "url": "oboemusicplayerandrecorder-0.5.4.aar",
          "size": 1776120,
          "sha512": "c91277ead4238fbb67b6fed0d296a4beac5af2078e1abf1a4f677c92deadfd6660ab89f6965c9c05d3d1fd3735ed9c9aa4a271c1555d5e03f6e4d791373e3446",
          "sha256": "fcb317f875a26d76e1e545d463cba26d49d55bc39676383e34822211a0fc97bc",
          "sha1": "98867a1a188575e5ba10af99f1e666b8c3a91db9",
          "md5": "128edc4cfd3a7dc71e4c415ce4c44928"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4.aar",
          "url": "oboemusicplayerandrecorder-0.5.4.aar",
          "size": 1776120,
          "sha512": "c91277ead4238fbb67b6fed0d296a4beac5af2078e1abf1a4f677c92deadfd6660ab89f6965c9c05d3d1fd3735ed9c9aa4a271c1555d5e03f6e4d791373e3446",
          "sha256": "fcb317f875a26d76e1e545d463cba26d49d55bc39676383e34822211a0fc97bc",
          "sha1": "98867a1a188575e5ba10af99f1e666b8c3a91db9",
          "md5": "128edc4cfd3a7dc71e4c415ce4c44928"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.4-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
