{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp13.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp13.aar",
          "size": 2523247,
          "sha512": "f7f4db4e4d0340e1eec20ad88d3cdf1a2369536bd0171785e37417f5c9636d947b91221eda40580abec67a7ddf2b34c642bd910509be0d8a06f9a9732b464e37",
          "sha256": "3e493b418ae419f9939bca3a0e8527149000c00ebb3d3f1e4ce37026f5430f96",
          "sha1": "d8473a8fb8168a7487afd8b03c7c341b185e8900",
          "md5": "a770dfc7f515cccf2d04fe99c918b322"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp13.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp13.aar",
          "size": 2523247,
          "sha512": "f7f4db4e4d0340e1eec20ad88d3cdf1a2369536bd0171785e37417f5c9636d947b91221eda40580abec67a7ddf2b34c642bd910509be0d8a06f9a9732b464e37",
          "sha256": "3e493b418ae419f9939bca3a0e8527149000c00ebb3d3f1e4ce37026f5430f96",
          "sha1": "d8473a8fb8168a7487afd8b03c7c341b185e8900",
          "md5": "a770dfc7f515cccf2d04fe99c918b322"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp13-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp13-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
