{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.7.aar",
          "url": "oboemusicplayerandrecorder-0.1.7.aar",
          "size": 1393917,
          "sha512": "9464b1dcf89a482d8ce6f52b1229bd55043233e39ecbe57ae5e0ab5471dd61f7d867822b275d2ffa67ababb18619974a8e642ec7d0ef8a9f1f53c147950d2ec9",
          "sha256": "2075a04f5431d33a70eebca3591f5050c4acce2028111c7e7d0871f5f701dbe8",
          "sha1": "0ca6db0551b1a0d080f460399ac20d0d03bc9451",
          "md5": "281e6ad3220e4ad0bd1a66892d2aa536"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.7.aar",
          "url": "oboemusicplayerandrecorder-0.1.7.aar",
          "size": 1393917,
          "sha512": "9464b1dcf89a482d8ce6f52b1229bd55043233e39ecbe57ae5e0ab5471dd61f7d867822b275d2ffa67ababb18619974a8e642ec7d0ef8a9f1f53c147950d2ec9",
          "sha256": "2075a04f5431d33a70eebca3591f5050c4acce2028111c7e7d0871f5f701dbe8",
          "sha1": "0ca6db0551b1a0d080f460399ac20d0d03bc9451",
          "md5": "281e6ad3220e4ad0bd1a66892d2aa536"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.7-sources.jar",
          "url": "oboemusicplayerandrecorder-0.1.7-sources.jar",
          "size": 3793,
          "sha512": "c832beb087193d87f6a9eaadd578110cd9b390d7d95f9b35aae55b6b2a71d2e2726fad5aebb65560c8257ff8ad9ef4182919a980ac9b2cd9bd57273447ce9388",
          "sha256": "3c20d5df961017a9b8eb42ead9df3c9cbfb4417621d916b03af597ed3aa5f7d3",
          "sha1": "33a28da687d1bdc3cf5d31460da074b04ca5eaa0",
          "md5": "bbf5f2c643d78b06bbd53854996c5865"
        }
      ]
    }
  ]
}
