{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.1-exp20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp20.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp20.aar",
          "size": 1773598,
          "sha512": "d5bb80cdc6491178949e44f94ed83f6bfa09fcc94ff44c584bd86d163e351733500b69fe7aec6c8c21c0cbbffc8661ce22891c075b6d648961cd4988534992ed",
          "sha256": "4ce0932a982f3aa3884f5c7d2317b5409e8a409e41abf2845235802b5ea4d318",
          "sha1": "3bdaeecd8f8862b073153dc0a46926ff4c5db555",
          "md5": "d4beede894198c4516b91db063d11801"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp20.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp20.aar",
          "size": 1773598,
          "sha512": "d5bb80cdc6491178949e44f94ed83f6bfa09fcc94ff44c584bd86d163e351733500b69fe7aec6c8c21c0cbbffc8661ce22891c075b6d648961cd4988534992ed",
          "sha256": "4ce0932a982f3aa3884f5c7d2317b5409e8a409e41abf2845235802b5ea4d318",
          "sha1": "3bdaeecd8f8862b073153dc0a46926ff4c5db555",
          "md5": "d4beede894198c4516b91db063d11801"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp20-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp20-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
