{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboenativemodule",
    "version": "1.1.4-exp10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp10.aar",
          "url": "oboenativemodule-1.1.4-exp10.aar",
          "size": 1385427,
          "sha512": "09dbb6d7f01e748ff390589b1f77b2b38ebfe937be014fe966d7306df0f468733c860b90cb2e6ffd8b850c8b40d6b5bb7aed8e29520bbd88759e944bba1d8a42",
          "sha256": "7968f8be4248a958b79bce5905b61e734793d2bddc7955b537b5a451985086af",
          "sha1": "de10f212fe5d28ed18aca76f995cbb7ba018d94a",
          "md5": "1b77cd1a034fa418d56857fc08e6230c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp10.aar",
          "url": "oboenativemodule-1.1.4-exp10.aar",
          "size": 1385427,
          "sha512": "09dbb6d7f01e748ff390589b1f77b2b38ebfe937be014fe966d7306df0f468733c860b90cb2e6ffd8b850c8b40d6b5bb7aed8e29520bbd88759e944bba1d8a42",
          "sha256": "7968f8be4248a958b79bce5905b61e734793d2bddc7955b537b5a451985086af",
          "sha1": "de10f212fe5d28ed18aca76f995cbb7ba018d94a",
          "md5": "1b77cd1a034fa418d56857fc08e6230c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp10-sources.jar",
          "url": "oboenativemodule-1.1.4-exp10-sources.jar",
          "size": 2793,
          "sha512": "0009b3074adcba4ea7aaa5d40d81b02d1c92dd55d2ee2021726fc393307127f03e1855aec8ec4dcb541d8237c9c2b8f99406d4ce050e27a22f8c8c19bea732ae",
          "sha256": "d8bc0619859c0810ebbf9a3a6bb5e8183f402991c5487bc56c914b01c41b0ef7",
          "sha1": "b6e53ca54d0bccb6d284d6c6d17a24cacb22c56b",
          "md5": "03cde79f7b1206f3969086e351a071ce"
        }
      ]
    }
  ]
}
