{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.2-exp7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp7.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp7.aar",
          "size": 1773874,
          "sha512": "f810fa3211edaf5afbb9a25fddbd5fec46aff22f5b0026284a9df4e5eea9b17de01be8b130cf1aa8d273883be738c6bbef7d33cc68865de36813694faaa29c87",
          "sha256": "467dfc6b4b05093c2b45cc1896c6700df73d9408b70018d2ca0e56ff043b803f",
          "sha1": "639efde3eba5184a672342d5e10056085e4cb44d",
          "md5": "823a26db9ad60c928f5f31041695136a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp7.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp7.aar",
          "size": 1773874,
          "sha512": "f810fa3211edaf5afbb9a25fddbd5fec46aff22f5b0026284a9df4e5eea9b17de01be8b130cf1aa8d273883be738c6bbef7d33cc68865de36813694faaa29c87",
          "sha256": "467dfc6b4b05093c2b45cc1896c6700df73d9408b70018d2ca0e56ff043b803f",
          "sha1": "639efde3eba5184a672342d5e10056085e4cb44d",
          "md5": "823a26db9ad60c928f5f31041695136a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp7-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp7-sources.jar",
          "size": 11247,
          "sha512": "16aa816706f4c0d185bfe7bc1bb239f0ea5a535f34435ef0896e14a5171a19348cdf6f3dfd9ca314ee9692844a41d3a2102ae3076d9daba61726d6c01de8953d",
          "sha256": "fdb2ffa8ad1c5750c1f0bc3eeb3d80b93b6c9af53174bb14bc2c9568d7f31bfa",
          "sha1": "cda2df24009dcfc7c13f84eb4aab672c3fa1f12a",
          "md5": "318db1e00241502f5c1919b0606270c8"
        }
      ]
    }
  ]
}
