{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp2.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp2.aar",
          "size": 1721700,
          "sha512": "5a8168a081ed51dcb1a8e6a51a34e73d1ce531f88fc08bf493ce87807c52d317556669c6ddf924698b9914638c6b6647a1ba7833d6e8a370fc40f101b0649dfb",
          "sha256": "38490bcba2cf9756ebd6cf8fa253cacd23a6d5382cef6e8c0ded967620d9e0a6",
          "sha1": "277ca0c48e5c896588bfaed3005b933bd417c252",
          "md5": "5226b8ce16a3c74ff91d376cda8e031a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp2.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp2.aar",
          "size": 1721700,
          "sha512": "5a8168a081ed51dcb1a8e6a51a34e73d1ce531f88fc08bf493ce87807c52d317556669c6ddf924698b9914638c6b6647a1ba7833d6e8a370fc40f101b0649dfb",
          "sha256": "38490bcba2cf9756ebd6cf8fa253cacd23a6d5382cef6e8c0ded967620d9e0a6",
          "sha1": "277ca0c48e5c896588bfaed3005b933bd417c252",
          "md5": "5226b8ce16a3c74ff91d376cda8e031a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp2-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp2-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
