{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboenativemodule",
    "version": "1.1.4-exp8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp8.aar",
          "url": "oboenativemodule-1.1.4-exp8.aar",
          "size": 1383275,
          "sha512": "680119011484564acc183abb36494ca0631ef821f2b53b9242306d6fbd7079e1914e028e1cdd9d828f692d6d0296c79b0fc9b53c5ec429a4ba82b2d848dadd11",
          "sha256": "14d5dfedcb0e4cc2168b61b686f5d674492c39b22fe041c944c04e1d64ddcaf9",
          "sha1": "7ccc50a94284e6dd8acccbee572e91c0d6469f3c",
          "md5": "adce746e75d1015ad90db456ada36ddd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp8.aar",
          "url": "oboenativemodule-1.1.4-exp8.aar",
          "size": 1383275,
          "sha512": "680119011484564acc183abb36494ca0631ef821f2b53b9242306d6fbd7079e1914e028e1cdd9d828f692d6d0296c79b0fc9b53c5ec429a4ba82b2d848dadd11",
          "sha256": "14d5dfedcb0e4cc2168b61b686f5d674492c39b22fe041c944c04e1d64ddcaf9",
          "sha1": "7ccc50a94284e6dd8acccbee572e91c0d6469f3c",
          "md5": "adce746e75d1015ad90db456ada36ddd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.1.4-exp8-sources.jar",
          "url": "oboenativemodule-1.1.4-exp8-sources.jar",
          "size": 2773,
          "sha512": "9528d55e192cd23183f60ec68a1a31aa4951e1f887f52623ff73034e52b15fa72ffead049e0f700299633235664e836e27a8e4337c0e994121e0589cc990617f",
          "sha256": "6d3460255b1a49e2f268f303b7c442e1b75ccc8b28f34c1ae4639e184cfcae17",
          "sha1": "7a49d083a19e3d8536fb03e5e903e0b62410e454",
          "md5": "3013618ef972ebc426f6b3515418ac9a"
        }
      ]
    }
  ]
}
