{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.11.aar",
          "url": "oboemusicplayerandrecorder-0.1.11.aar",
          "size": 1395740,
          "sha512": "fe8c836a34eaf37ee1afab4cfcc3fe561d965702dcc41cf1ba9ad4a2c8976d2c407f43bf8b95c08755e26477c230da698598c6e9ac13dce3581799ff61f0db36",
          "sha256": "aea18ef80c6791ecd53e97ddd6312066a49c0c79f17a0ae32f0b6f79a67ad56a",
          "sha1": "fc9294b619a16f0b9fdc21ad6c074fc0d528df10",
          "md5": "bc9a0169f690b84b005523c2055ec60d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.11.aar",
          "url": "oboemusicplayerandrecorder-0.1.11.aar",
          "size": 1395740,
          "sha512": "fe8c836a34eaf37ee1afab4cfcc3fe561d965702dcc41cf1ba9ad4a2c8976d2c407f43bf8b95c08755e26477c230da698598c6e9ac13dce3581799ff61f0db36",
          "sha256": "aea18ef80c6791ecd53e97ddd6312066a49c0c79f17a0ae32f0b6f79a67ad56a",
          "sha1": "fc9294b619a16f0b9fdc21ad6c074fc0d528df10",
          "md5": "bc9a0169f690b84b005523c2055ec60d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.11-sources.jar",
          "url": "oboemusicplayerandrecorder-0.1.11-sources.jar",
          "size": 3821,
          "sha512": "91c568d6dc83a86595f95680dc999a4b61e5bb74cc3a85fd487786c2d006146e313f1b09b125264a6d43d187d54fd46286e9ea6fb268e33a2ce6fa3dc1a38018",
          "sha256": "f47825bcd4f94bbb568ed78e6a54e067216b683d9b58fc89a7f993f2af2f8c93",
          "sha1": "a91cb225c05abbc57c96eb7ef4b514bdeb1eb0a0",
          "md5": "16353113fd70c82d0df03a9e40d5a915"
        }
      ]
    }
  ]
}
