{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.1-exp5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp5.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp5.aar",
          "size": 1774140,
          "sha512": "78ad46899a605f918d6acc853c318fcd6248af3e0e1981753553c55bcf7699fb250fd5b58333ae76e41080bda1ab6d10de71c1de997aea178bb31be38ed64cee",
          "sha256": "9b3c474696e566a755cc198e4cc6eca6179a288b9b6a8d0338a5a80a8a52bb9e",
          "sha1": "772215db87c1d3b9504223491399a5dbae21e95f",
          "md5": "7222cad4e4195a9072aebdb6a99040bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp5.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp5.aar",
          "size": 1774140,
          "sha512": "78ad46899a605f918d6acc853c318fcd6248af3e0e1981753553c55bcf7699fb250fd5b58333ae76e41080bda1ab6d10de71c1de997aea178bb31be38ed64cee",
          "sha256": "9b3c474696e566a755cc198e4cc6eca6179a288b9b6a8d0338a5a80a8a52bb9e",
          "sha1": "772215db87c1d3b9504223491399a5dbae21e95f",
          "md5": "7222cad4e4195a9072aebdb6a99040bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp5-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp5-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
