{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.2.aar",
          "url": "oboemusicplayerandrecorder-0.6.2.aar",
          "size": 1780615,
          "sha512": "d76324c0c9de5e9f1c64b9cc958b46a462efd74ba2c97acfb410bf90bb827e31a9e01062aaeb9ba92a08ce216c90e855a54f22690a9faa8e57cd161ddcf638c8",
          "sha256": "17a8e87859a175225b9ccbb379d74d81a2889d3296d06b1fd8787170e4423467",
          "sha1": "115ee9058992b81151a31fd84b94d16fe7d20da2",
          "md5": "fb6b563798a1a77bbc6daef73f6e6edf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.2.aar",
          "url": "oboemusicplayerandrecorder-0.6.2.aar",
          "size": 1780615,
          "sha512": "d76324c0c9de5e9f1c64b9cc958b46a462efd74ba2c97acfb410bf90bb827e31a9e01062aaeb9ba92a08ce216c90e855a54f22690a9faa8e57cd161ddcf638c8",
          "sha256": "17a8e87859a175225b9ccbb379d74d81a2889d3296d06b1fd8787170e4423467",
          "sha1": "115ee9058992b81151a31fd84b94d16fe7d20da2",
          "md5": "fb6b563798a1a77bbc6daef73f6e6edf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.2-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.2-sources.jar",
          "size": 11311,
          "sha512": "ee3ff522d46c9d942c4d146783036e4dd78326512004021f628b1e6b5764625f2d8c596bfb5e2a4dc462cc362d1cc25a12686eca1292e83ab74a0fe3c7f823fa",
          "sha256": "5e5ca1353c974b6533c5bfc6359927a369f7afb6001bd8b3602f02e145458ee0",
          "sha1": "f54d90c4deba5e5e8bdf6e259922830acac21fc3",
          "md5": "4dff1a0bdc832a8903dd7b39285dbc37"
        }
      ]
    }
  ]
}
