{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.1-exp17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp17.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp17.aar",
          "size": 1772089,
          "sha512": "cc476f3b8d8c1458b9581262f2440c0d0c08d89b6a9a1ccd7a8208f0192eaba6fe10f13e102a407f4c47899b6cc36f6f75a2f53401b59ebc06c5abd81767fc7b",
          "sha256": "97f70a7a4333626eec82e3660ea76d6f6c91c21ebdafd357dc934f0474c06dd6",
          "sha1": "9a06ff88b4f50b44e4185b1eda13076f89e9871f",
          "md5": "73df0ee82832b7c5f74d29311db471c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp17.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp17.aar",
          "size": 1772089,
          "sha512": "cc476f3b8d8c1458b9581262f2440c0d0c08d89b6a9a1ccd7a8208f0192eaba6fe10f13e102a407f4c47899b6cc36f6f75a2f53401b59ebc06c5abd81767fc7b",
          "sha256": "97f70a7a4333626eec82e3660ea76d6f6c91c21ebdafd357dc934f0474c06dd6",
          "sha1": "9a06ff88b4f50b44e4185b1eda13076f89e9871f",
          "md5": "73df0ee82832b7c5f74d29311db471c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp17-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp17-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
