{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.8-exp1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.8-exp1.aar",
          "url": "oboemusicplayerandrecorder-0.2.8-exp1.aar",
          "size": 1676460,
          "sha512": "0df8416151f13db1e631cd1e8124cb9d8f7835465f34977bac8289edd9bead1071afa237ea44926d6baeb5afc58d677608e5c1047fb9751add12447e040984c6",
          "sha256": "c10308d1923ee8af4b8a9065ce1624c5504114ad8499952bbcd20d2aad595eb4",
          "sha1": "6f4e4643092343624bbfc9033dc2eb5c3a35886f",
          "md5": "8770d1da419c06c70af88d220a05ae09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.8-exp1.aar",
          "url": "oboemusicplayerandrecorder-0.2.8-exp1.aar",
          "size": 1676460,
          "sha512": "0df8416151f13db1e631cd1e8124cb9d8f7835465f34977bac8289edd9bead1071afa237ea44926d6baeb5afc58d677608e5c1047fb9751add12447e040984c6",
          "sha256": "c10308d1923ee8af4b8a9065ce1624c5504114ad8499952bbcd20d2aad595eb4",
          "sha1": "6f4e4643092343624bbfc9033dc2eb5c3a35886f",
          "md5": "8770d1da419c06c70af88d220a05ae09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.8-exp1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.8-exp1-sources.jar",
          "size": 7141,
          "sha512": "f41bb29276cd248694ae3da3b57110b6260297874a8d0e089ea3a88fdfee43ab1f2534bb574d267cb695a6e172f7843d7a0357b4cbc02ceb4e132393a7a31df4",
          "sha256": "230bcc1b87ad33eaf9740ad0584a33048f49c029d289ef3e6c7b59cc89574760",
          "sha1": "23d3c6893115aa340ef69843bbdca4e03f2e69e2",
          "md5": "5109f12a00a732af2cb133a6ac5387a1"
        }
      ]
    }
  ]
}
