{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.1-exp13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp13.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp13.aar",
          "size": 1772441,
          "sha512": "5dae0a0990f38ab557570b5b7ad9aeb05347a134e59e7bc0e46b123e27ceaac8346920df5a13e8b23250b9a78a83d145090aef019684539812115b8eda6a89d3",
          "sha256": "49c786bb97dc48b5ba8748b21c0671fbc5a94e29f4a77f8ff041f30c0ed81981",
          "sha1": "18fff344c031b0ddf38565e1b8cc052c40b00114",
          "md5": "01bd11ca6a61d430c4c3a5d14113a00c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp13.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp13.aar",
          "size": 1772441,
          "sha512": "5dae0a0990f38ab557570b5b7ad9aeb05347a134e59e7bc0e46b123e27ceaac8346920df5a13e8b23250b9a78a83d145090aef019684539812115b8eda6a89d3",
          "sha256": "49c786bb97dc48b5ba8748b21c0671fbc5a94e29f4a77f8ff041f30c0ed81981",
          "sha1": "18fff344c031b0ddf38565e1b8cc052c40b00114",
          "md5": "01bd11ca6a61d430c4c3a5d14113a00c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp13-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp13-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
