{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.5-exp3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp3.aar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp3.aar",
          "size": 1661843,
          "sha512": "23c32e259e00bd0c175f1bfb800a3be6c5af909971ddb5a717029b3a9a4b854b81c50b883470db0c8c3718f1cdae40cd3b51f779b9b36822ca7c4809eee25e7f",
          "sha256": "b34bae078b6c197f46ae8c680c4e3f581f39b33e8f9c612aa5ddd9f6c7478078",
          "sha1": "8ad73e440cc755e89f70e186b423faffb12cf5c6",
          "md5": "00440f7797bf7dec62c873793ca54424"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp3.aar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp3.aar",
          "size": 1661843,
          "sha512": "23c32e259e00bd0c175f1bfb800a3be6c5af909971ddb5a717029b3a9a4b854b81c50b883470db0c8c3718f1cdae40cd3b51f779b9b36822ca7c4809eee25e7f",
          "sha256": "b34bae078b6c197f46ae8c680c4e3f581f39b33e8f9c612aa5ddd9f6c7478078",
          "sha1": "8ad73e440cc755e89f70e186b423faffb12cf5c6",
          "md5": "00440f7797bf7dec62c873793ca54424"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp3-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp3-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
