{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.4.aar",
          "url": "oboemusicplayerandrecorder-0.4.4.aar",
          "size": 1764924,
          "sha512": "92ede58ae6ea3c3ca6f7e525b38a7c22909ac117fef840463fbf5ab1a24f2613affe62e4e161b90e5f856c8cbdb719f80a9626dfee9c8ba483c923ead8009052",
          "sha256": "07cb0a1ad8acf5ef098022543f010acb2dad4bcf9748a102c005b971507b2997",
          "sha1": "afc4c34b18295a5464922269f0a6c79626adf9f9",
          "md5": "f7027620903e065ce66156485aba365f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.4.aar",
          "url": "oboemusicplayerandrecorder-0.4.4.aar",
          "size": 1764924,
          "sha512": "92ede58ae6ea3c3ca6f7e525b38a7c22909ac117fef840463fbf5ab1a24f2613affe62e4e161b90e5f856c8cbdb719f80a9626dfee9c8ba483c923ead8009052",
          "sha256": "07cb0a1ad8acf5ef098022543f010acb2dad4bcf9748a102c005b971507b2997",
          "sha1": "afc4c34b18295a5464922269f0a6c79626adf9f9",
          "md5": "f7027620903e065ce66156485aba365f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.4-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.4-sources.jar",
          "size": 11248,
          "sha512": "54abe542bbcb2149b6dfcc9fa3db8879ba66d52c34eca30d2710aeadd568c447a996ba53c4f82599a2ce7f95f67f605284cc658b10590fdfd9989b922c4c191d",
          "sha256": "dca2a5b49c2f10eccc31cd143028169fd5d5eddafc5814edbafe0b2feffc2785",
          "sha1": "4bff27bb879ea4051e8c28b4ef3c872fb9aac2ef",
          "md5": "4292b22e7e0eef3430de175ec2186a82"
        }
      ]
    }
  ]
}
