{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.3.aar",
          "url": "oboemusicplayerandrecorder-0.1.3.aar",
          "size": 1393899,
          "sha512": "844faee1c55734d55a91dc380a38bb1016d26d75a874e3ceacc40e68a7b2b4bb4d036c6f8f5fdafaab319e510eb77bcbab19a2f2caa53116c60f50a7ce891727",
          "sha256": "be0d0d750c252a785c85104b630ed82612960f73a8835092082c0a24798ac4c2",
          "sha1": "07acd8c4bc849721e069f1b61c2e694e76496f11",
          "md5": "7cb1513e1a655773f31abde68e42fdb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.3.aar",
          "url": "oboemusicplayerandrecorder-0.1.3.aar",
          "size": 1393899,
          "sha512": "844faee1c55734d55a91dc380a38bb1016d26d75a874e3ceacc40e68a7b2b4bb4d036c6f8f5fdafaab319e510eb77bcbab19a2f2caa53116c60f50a7ce891727",
          "sha256": "be0d0d750c252a785c85104b630ed82612960f73a8835092082c0a24798ac4c2",
          "sha1": "07acd8c4bc849721e069f1b61c2e694e76496f11",
          "md5": "7cb1513e1a655773f31abde68e42fdb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.3-sources.jar",
          "url": "oboemusicplayerandrecorder-0.1.3-sources.jar",
          "size": 3793,
          "sha512": "c832beb087193d87f6a9eaadd578110cd9b390d7d95f9b35aae55b6b2a71d2e2726fad5aebb65560c8257ff8ad9ef4182919a980ac9b2cd9bd57273447ce9388",
          "sha256": "3c20d5df961017a9b8eb42ead9df3c9cbfb4417621d916b03af597ed3aa5f7d3",
          "sha1": "33a28da687d1bdc3cf5d31460da074b04ca5eaa0",
          "md5": "bbf5f2c643d78b06bbd53854996c5865"
        }
      ]
    }
  ]
}
