{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp5.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp5.aar",
          "size": 1719807,
          "sha512": "f7a39ab1ee003f095b12c7dfbcc78d159c0ddf107e0cbfcb49a5381c88457b8333adb728b2989f9ceef1ec3962c1a00159904a88f563f191b8efe973c73e7e07",
          "sha256": "d1e3d66fa231839b445c313b247ec28f02041f92806282168b2dd7cd7adfe322",
          "sha1": "6b2346f5717f9ec7c3f40477fbb789a708b1c4ee",
          "md5": "aecbdaa5f64b6183ee3e52899278f1e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp5.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp5.aar",
          "size": 1719807,
          "sha512": "f7a39ab1ee003f095b12c7dfbcc78d159c0ddf107e0cbfcb49a5381c88457b8333adb728b2989f9ceef1ec3962c1a00159904a88f563f191b8efe973c73e7e07",
          "sha256": "d1e3d66fa231839b445c313b247ec28f02041f92806282168b2dd7cd7adfe322",
          "sha1": "6b2346f5717f9ec7c3f40477fbb789a708b1c4ee",
          "md5": "aecbdaa5f64b6183ee3e52899278f1e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp5-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp5-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
