{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.10.aar",
          "url": "oboemusicplayerandrecorder-0.1.10.aar",
          "size": 1395466,
          "sha512": "860196eb88ecb54928e1ebfa063948ff6f7db230e9a6c50e2f31e0ca39b00640a2ba03364f1d10706875b065f38c4c3a88eb0a841a295766875c02eb7f539910",
          "sha256": "48abbc4d539c8d00532048d78640379402652aa551d7676a48208d59f88c74b6",
          "sha1": "becad4ef85ce5b4711e5d7fae25e466bf14d982b",
          "md5": "5627e865144186890f692c9724d2ddcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.10.aar",
          "url": "oboemusicplayerandrecorder-0.1.10.aar",
          "size": 1395466,
          "sha512": "860196eb88ecb54928e1ebfa063948ff6f7db230e9a6c50e2f31e0ca39b00640a2ba03364f1d10706875b065f38c4c3a88eb0a841a295766875c02eb7f539910",
          "sha256": "48abbc4d539c8d00532048d78640379402652aa551d7676a48208d59f88c74b6",
          "sha1": "becad4ef85ce5b4711e5d7fae25e466bf14d982b",
          "md5": "5627e865144186890f692c9724d2ddcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.10-sources.jar",
          "url": "oboemusicplayerandrecorder-0.1.10-sources.jar",
          "size": 3821,
          "sha512": "91c568d6dc83a86595f95680dc999a4b61e5bb74cc3a85fd487786c2d006146e313f1b09b125264a6d43d187d54fd46286e9ea6fb268e33a2ce6fa3dc1a38018",
          "sha256": "f47825bcd4f94bbb568ed78e6a54e067216b683d9b58fc89a7f993f2af2f8c93",
          "sha1": "a91cb225c05abbc57c96eb7ef4b514bdeb1eb0a0",
          "md5": "16353113fd70c82d0df03a9e40d5a915"
        }
      ]
    }
  ]
}
