{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.5-exp13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp13.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp13.aar",
          "size": 1791448,
          "sha512": "d0f9b12f94b9f2fc391397d2d0505fe0ac219b07f1dc39085264bd8b084a1ae3e6b9d02e89195fe07490dc472d8e413b4333f4022897b1d6ad13d5988dac2645",
          "sha256": "ac0b074eb3c22e1084bc4ccc7bee85a3af6287658e4a1fb0ca3bb0876cf9f629",
          "sha1": "b76fabaa59aeb5f62da46fa1694e2c179bf2f881",
          "md5": "14188122ab7b07f947397a9fd4285dc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp13.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp13.aar",
          "size": 1791448,
          "sha512": "d0f9b12f94b9f2fc391397d2d0505fe0ac219b07f1dc39085264bd8b084a1ae3e6b9d02e89195fe07490dc472d8e413b4333f4022897b1d6ad13d5988dac2645",
          "sha256": "ac0b074eb3c22e1084bc4ccc7bee85a3af6287658e4a1fb0ca3bb0876cf9f629",
          "sha1": "b76fabaa59aeb5f62da46fa1694e2c179bf2f881",
          "md5": "14188122ab7b07f947397a9fd4285dc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp13-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp13-sources.jar",
          "size": 11747,
          "sha512": "7b7eb4724f16554e3201418767249f5ef18c8e2e89f56c295d5bd70e4f0403d693ea891293fd7f04c1a6bd5ad1c790be9e2f71b7857402dfe653541780b22952",
          "sha256": "0e92ba43a0292bf9f3a9ed97dc12674bc92e81841f6ec27157e0a5bf7af94240",
          "sha1": "075ca827e780d9b29126c4d23f9c969c21376ee7",
          "md5": "ec6bc1d27aaff8b23d4a06863de222dd"
        }
      ]
    }
  ]
}
