{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.5-exp2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp2.aar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp2.aar",
          "size": 1661852,
          "sha512": "0598e2ba1afa0a7f02bb7ab0667bc95204a1ded0a33c350c17d31a231651f14af62b52c7fcd2f2b2f8547e38b06a5ec7abe612c0fb54f77fcec3226a0f7e1bb3",
          "sha256": "94a7e3ab71e063ebd64ebfe2611f4cefed7455ced227e3ed6e296663407a3381",
          "sha1": "c6211dfb408cbfa28ceddfb29a576199fbbded9b",
          "md5": "da102bb5eeb5774eed82f97e08f3ed8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp2.aar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp2.aar",
          "size": 1661852,
          "sha512": "0598e2ba1afa0a7f02bb7ab0667bc95204a1ded0a33c350c17d31a231651f14af62b52c7fcd2f2b2f8547e38b06a5ec7abe612c0fb54f77fcec3226a0f7e1bb3",
          "sha256": "94a7e3ab71e063ebd64ebfe2611f4cefed7455ced227e3ed6e296663407a3381",
          "sha1": "c6211dfb408cbfa28ceddfb29a576199fbbded9b",
          "md5": "da102bb5eeb5774eed82f97e08f3ed8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp2-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp2-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
