{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.5-exp6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp6.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp6.aar",
          "size": 1794191,
          "sha512": "ad026f33186bd0a9667dd5a5bf524a3d55f57902fc1fde6338e8d3b48fe8d1ad72695a44bdd789001d4619930340fbb7b96501e8d8f944930ca693ad4ed454da",
          "sha256": "0068fd178c92ce0909f5906293609640d3c2912c2f80359c183ea1a7166bdd57",
          "sha1": "ef1b5f9747fe3b0c67545bde10caf7644b68a86c",
          "md5": "d188b33ce6e8edc7e64d7955a6be46bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp6.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp6.aar",
          "size": 1794191,
          "sha512": "ad026f33186bd0a9667dd5a5bf524a3d55f57902fc1fde6338e8d3b48fe8d1ad72695a44bdd789001d4619930340fbb7b96501e8d8f944930ca693ad4ed454da",
          "sha256": "0068fd178c92ce0909f5906293609640d3c2912c2f80359c183ea1a7166bdd57",
          "sha1": "ef1b5f9747fe3b0c67545bde10caf7644b68a86c",
          "md5": "d188b33ce6e8edc7e64d7955a6be46bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp6-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp6-sources.jar",
          "size": 11798,
          "sha512": "a95018125d5c88c6ebda06cbdf82ccb57fd4a8f14baeffabe30a65c32e2b3cd624a329f856f38bbf1a8867869d107f627ce5518c74b9d83a68b170e7edc9193d",
          "sha256": "544a3e51e68382f26dc4cf6298bdc11502e3f157a0adaab4ead598aece1f89d2",
          "sha1": "d029452d93e418203958db094d7d00f8fe1fd4d5",
          "md5": "a8762aab7e923ac53f1130e661369647"
        }
      ]
    }
  ]
}
