{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.5-exp9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp9.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp9.aar",
          "size": 1789655,
          "sha512": "b7ab777ea21612b48e88ea670e0c340b75626cbc67580b0d3405d0fb578c31735b62e8dc2f7290c30953282ebace16daec5859f6eb3a3d761270d06fa51ceff8",
          "sha256": "b91813f62ec7a017bc253af4b6a3cb58bafbfdd2bea4567ea09a6f4da91b01b6",
          "sha1": "a2a11b56293245ec079dfbcc9504abd60ff85fa9",
          "md5": "22852e0100d51e283076e9832022b0c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp9.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp9.aar",
          "size": 1789655,
          "sha512": "b7ab777ea21612b48e88ea670e0c340b75626cbc67580b0d3405d0fb578c31735b62e8dc2f7290c30953282ebace16daec5859f6eb3a3d761270d06fa51ceff8",
          "sha256": "b91813f62ec7a017bc253af4b6a3cb58bafbfdd2bea4567ea09a6f4da91b01b6",
          "sha1": "a2a11b56293245ec079dfbcc9504abd60ff85fa9",
          "md5": "22852e0100d51e283076e9832022b0c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-exp9-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.5-exp9-sources.jar",
          "size": 11747,
          "sha512": "7b7eb4724f16554e3201418767249f5ef18c8e2e89f56c295d5bd70e4f0403d693ea891293fd7f04c1a6bd5ad1c790be9e2f71b7857402dfe653541780b22952",
          "sha256": "0e92ba43a0292bf9f3a9ed97dc12674bc92e81841f6ec27157e0a5bf7af94240",
          "sha1": "075ca827e780d9b29126c4d23f9c969c21376ee7",
          "md5": "ec6bc1d27aaff8b23d4a06863de222dd"
        }
      ]
    }
  ]
}
