{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp.aar",
          "size": 1719955,
          "sha512": "1a77a88746a320dc4c652378f17d13dc20c7c8e9cb34638e2b0babf582c19c1b290a135af2c8a430d50bc83a0a3c0fc53e2ef21c3e07ff034c493ad63c76b1c2",
          "sha256": "d3453e4149e7f5fd08aec0e1e3daaa098536c3a11ca1eb550f65d8f2598e27ae",
          "sha1": "03a4a220a2face35c2a4ac7cdb4a9e11c4e65473",
          "md5": "38e16650cf383f4241ffd0d8f1c77159"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp.aar",
          "size": 1719955,
          "sha512": "1a77a88746a320dc4c652378f17d13dc20c7c8e9cb34638e2b0babf582c19c1b290a135af2c8a430d50bc83a0a3c0fc53e2ef21c3e07ff034c493ad63c76b1c2",
          "sha256": "d3453e4149e7f5fd08aec0e1e3daaa098536c3a11ca1eb550f65d8f2598e27ae",
          "sha1": "03a4a220a2face35c2a4ac7cdb4a9e11c4e65473",
          "md5": "38e16650cf383f4241ffd0d8f1c77159"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
