{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.5-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-4.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-4.aar",
          "size": 1795746,
          "sha512": "890c54292d5d5d2d26854c193de5dc7f41c1822f4c8ad0e1d832f0b0bb4e44c6fc7c79a35501389526e33b9f9e85743b4240458d9cac4f4a35e82ccf74869c28",
          "sha256": "1c9671406c913934114bd5f34332ff8d3a47cf97121336b40a84be393f0387a0",
          "sha1": "1784f374fd314b9a99033ebe2759878e8d232816",
          "md5": "6fe2d8632e4130bd6071c0ed0b71b04d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-4.aar",
          "url": "oboemusicplayerandrecorder-0.6.5-4.aar",
          "size": 1795746,
          "sha512": "890c54292d5d5d2d26854c193de5dc7f41c1822f4c8ad0e1d832f0b0bb4e44c6fc7c79a35501389526e33b9f9e85743b4240458d9cac4f4a35e82ccf74869c28",
          "sha256": "1c9671406c913934114bd5f34332ff8d3a47cf97121336b40a84be393f0387a0",
          "sha1": "1784f374fd314b9a99033ebe2759878e8d232816",
          "md5": "6fe2d8632e4130bd6071c0ed0b71b04d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.5-4-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.5-4-sources.jar",
          "size": 11885,
          "sha512": "4747e99b085df38e9ac8f9b72397dac2036214b4d63d7d02f097af443349954b7dceea28321cbd8740aa5377c0c2c79943c7adbb0a029249f74f648b864f8cc5",
          "sha256": "ee654daf5e4d467dd024782590abd354506b83d1e44855eb9d6e87ebb161da8c",
          "sha1": "612ef51e69b69f13e574da93feff528579ffa6de",
          "md5": "08d071c7161cbefeb27af461cfd0d886"
        }
      ]
    }
  ]
}
