{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboenativemodule",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "oboenativemodule-1.0.6.aar",
          "url": "oboenativemodule-1.0.6.aar",
          "size": 1377657,
          "sha512": "5aaa90952bd8bd46ac28f94d73ce7196db9a727a4aa099c2c61d46dc03f97d2dd855d935955605406331fa339aaaefca0941b60a6e98193ce17df730b0b07c20",
          "sha256": "8e04e122885dbfb1025fcdb4a1b65d8de2a96473b0c115da2dd2a761da3b1d3b",
          "sha1": "d413a1507c06bcbe2e9de6bc74cdaeb6c7be15b6",
          "md5": "1a502175093cbf7846f7a8b626ec1f42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.0.6.aar",
          "url": "oboenativemodule-1.0.6.aar",
          "size": 1377657,
          "sha512": "5aaa90952bd8bd46ac28f94d73ce7196db9a727a4aa099c2c61d46dc03f97d2dd855d935955605406331fa339aaaefca0941b60a6e98193ce17df730b0b07c20",
          "sha256": "8e04e122885dbfb1025fcdb4a1b65d8de2a96473b0c115da2dd2a761da3b1d3b",
          "sha1": "d413a1507c06bcbe2e9de6bc74cdaeb6c7be15b6",
          "md5": "1a502175093cbf7846f7a8b626ec1f42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboenativemodule-1.0.6-sources.jar",
          "url": "oboenativemodule-1.0.6-sources.jar",
          "size": 2722,
          "sha512": "7b469088911cd4dbdb891530b3f230ed3e6d63c60a2991a3c8db951fe09f1ebb3a25b89e7d98a41f4e21a75e0f8f79fed4c5ab9c2ceab3c3e22ec145fa018c48",
          "sha256": "da5b3ea193d2f01b3ddc40a025eb7980744245fb7f6caa59ec0a701d79964176",
          "sha1": "2099c6fcfced2d60c5279215633e13324308deeb",
          "md5": "c002ccb70195b6562d350b9da73c7c2e"
        }
      ]
    }
  ]
}
