{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.2-exp6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp6.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp6.aar",
          "size": 1773814,
          "sha512": "27013c299ef0f575100fa0d27dbf7db521eea27a7f361037332f905a48dbe7b4469380c52644c0385126b449d08c8fbd39d5662185dd19861a29312b387acfa1",
          "sha256": "d0bab31224ab5b06f5426453ff904374d9b9b3aa405f8909c96754699c3b9814",
          "sha1": "0170b33683b950f456c02404e42909ebe6c2f99f",
          "md5": "6ceb019f7189dc817d76b533532e2ad7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp6.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp6.aar",
          "size": 1773814,
          "sha512": "27013c299ef0f575100fa0d27dbf7db521eea27a7f361037332f905a48dbe7b4469380c52644c0385126b449d08c8fbd39d5662185dd19861a29312b387acfa1",
          "sha256": "d0bab31224ab5b06f5426453ff904374d9b9b3aa405f8909c96754699c3b9814",
          "sha1": "0170b33683b950f456c02404e42909ebe6c2f99f",
          "md5": "6ceb019f7189dc817d76b533532e2ad7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp6-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp6-sources.jar",
          "size": 11247,
          "sha512": "16aa816706f4c0d185bfe7bc1bb239f0ea5a535f34435ef0896e14a5171a19348cdf6f3dfd9ca314ee9692844a41d3a2102ae3076d9daba61726d6c01de8953d",
          "sha256": "fdb2ffa8ad1c5750c1f0bc3eeb3d80b93b6c9af53174bb14bc2c9568d7f31bfa",
          "sha1": "cda2df24009dcfc7c13f84eb4aab672c3fa1f12a",
          "md5": "318db1e00241502f5c1919b0606270c8"
        }
      ]
    }
  ]
}
