{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.2-exp1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp1.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp1.aar",
          "size": 1741202,
          "sha512": "293d9810f8de90d73fcb2d7fd3df17198a0fa757ef36651157aaf42d433d45bea15b654efc883bb9a31df0e1d479c11aef3c31c5b67d27483e3de90ec50f4520",
          "sha256": "59dca870f53e024a94d12bd760ce72bdcabcabbb43a994050790d6dfea8f8b42",
          "sha1": "8c7ecb7fb22d753017b877876656bce9f5222808",
          "md5": "a312edc4b6a6f7d220cb5caaf0f80165"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp1.aar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp1.aar",
          "size": 1741202,
          "sha512": "293d9810f8de90d73fcb2d7fd3df17198a0fa757ef36651157aaf42d433d45bea15b654efc883bb9a31df0e1d479c11aef3c31c5b67d27483e3de90ec50f4520",
          "sha256": "59dca870f53e024a94d12bd760ce72bdcabcabbb43a994050790d6dfea8f8b42",
          "sha1": "8c7ecb7fb22d753017b877876656bce9f5222808",
          "md5": "a312edc4b6a6f7d220cb5caaf0f80165"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.2-exp1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.2-exp1-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
