{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.7-exp1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7-exp1.aar",
          "url": "oboemusicplayerandrecorder-0.2.7-exp1.aar",
          "size": 1677505,
          "sha512": "98530c753693418d7af842a814ae647c8e72a67f4a71c1d9930d5885af545efc8a96158bb7ad0eb09f23fce24e57f9a507979dbe10d5c21be203d332ea133f9e",
          "sha256": "0b3982f07a40c72081c02334fcdfe0efb41fd718c0a65ef6c213d183f84a973d",
          "sha1": "6d5ae69f611720556903fefd4eb9d378e33b0688",
          "md5": "9ad5c7ffdcd7d4143111b1662a6ca4ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7-exp1.aar",
          "url": "oboemusicplayerandrecorder-0.2.7-exp1.aar",
          "size": 1677505,
          "sha512": "98530c753693418d7af842a814ae647c8e72a67f4a71c1d9930d5885af545efc8a96158bb7ad0eb09f23fce24e57f9a507979dbe10d5c21be203d332ea133f9e",
          "sha256": "0b3982f07a40c72081c02334fcdfe0efb41fd718c0a65ef6c213d183f84a973d",
          "sha1": "6d5ae69f611720556903fefd4eb9d378e33b0688",
          "md5": "9ad5c7ffdcd7d4143111b1662a6ca4ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.7-exp1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.7-exp1-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
