{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.0.aar",
          "url": "oboemusicplayerandrecorder-0.8.0.aar",
          "size": 2357897,
          "sha512": "8100712239ad4a5bf8c19843acaccf6b750940c25523654d2e140cf0276a0c3c05f74578b1be49ec812be4da0625fe531250449a879232f3bb3137379e173207",
          "sha256": "dc953121608f8d4ebd558d881be24b17ac498ccd2ae26cec9efd813c21e81b11",
          "sha1": "e15fd348bc7dbb8236ff0a482e9627b036c64204",
          "md5": "5d9bcd7b99878b5c56eaaf1726f679f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.0.aar",
          "url": "oboemusicplayerandrecorder-0.8.0.aar",
          "size": 2357897,
          "sha512": "8100712239ad4a5bf8c19843acaccf6b750940c25523654d2e140cf0276a0c3c05f74578b1be49ec812be4da0625fe531250449a879232f3bb3137379e173207",
          "sha256": "dc953121608f8d4ebd558d881be24b17ac498ccd2ae26cec9efd813c21e81b11",
          "sha1": "e15fd348bc7dbb8236ff0a482e9627b036c64204",
          "md5": "5d9bcd7b99878b5c56eaaf1726f679f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.8.0-sources.jar",
          "url": "oboemusicplayerandrecorder-0.8.0-sources.jar",
          "size": 24475,
          "sha512": "42e875f68aab26e48f29f9d8f1cc3473eb82230860e2c145b8c485411426c6a7e5dbecc68a89047ff842f7a0fc634b022cf66037943d49254d69e357eed19d63",
          "sha256": "f5dbb1dd8283a298316b74069142ad30373186051e6232ccd3f1cf3ad7b342c5",
          "sha1": "f6827f0222c620414972acb36a27fc778a77c5ad",
          "md5": "b5209d53931e049df10184391de82e7f"
        }
      ]
    }
  ]
}
