{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.4-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4-2.aar",
          "url": "oboemusicplayerandrecorder-0.5.4-2.aar",
          "size": 1776725,
          "sha512": "d914a94cef135f1022b2f71038a60cebab9a8566bb74d1c406e5a8496440964f3eec6b629acc055628a803ec6f745a8bfe81718e61d2ed0477b250ca7dd8306f",
          "sha256": "e22c9604ea74762e167d4eee98d4bb486285a007f25eadbe2585227a0321ebb8",
          "sha1": "3fb038dc8a79068712d5f3c553c94521be1f9184",
          "md5": "bffbdec619526c99b0fee433b3e4d4b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4-2.aar",
          "url": "oboemusicplayerandrecorder-0.5.4-2.aar",
          "size": 1776725,
          "sha512": "d914a94cef135f1022b2f71038a60cebab9a8566bb74d1c406e5a8496440964f3eec6b629acc055628a803ec6f745a8bfe81718e61d2ed0477b250ca7dd8306f",
          "sha256": "e22c9604ea74762e167d4eee98d4bb486285a007f25eadbe2585227a0321ebb8",
          "sha1": "3fb038dc8a79068712d5f3c553c94521be1f9184",
          "md5": "bffbdec619526c99b0fee433b3e4d4b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4-2-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.4-2-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
