{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.4.aar",
          "url": "oboemusicplayerandrecorder-0.2.4.aar",
          "size": 1662594,
          "sha512": "fc9a6b70e4697961c609ba1126605bf7b9dce831902e13a0589608089876fcaaf894c6ba08f469f095b98aad4c5f96f69ea218198378ad05dab0773e8d0082ff",
          "sha256": "efcf43cd95a1d9fcdb465f46caa97ec6f0cfebaefabc4a9e552215d73278842e",
          "sha1": "3a2b4466c6a5dd42b131f1a904cfb8ea68fee7d1",
          "md5": "b20c18daeb1e279c33f0f2f0de0840d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.4.aar",
          "url": "oboemusicplayerandrecorder-0.2.4.aar",
          "size": 1662594,
          "sha512": "fc9a6b70e4697961c609ba1126605bf7b9dce831902e13a0589608089876fcaaf894c6ba08f469f095b98aad4c5f96f69ea218198378ad05dab0773e8d0082ff",
          "sha256": "efcf43cd95a1d9fcdb465f46caa97ec6f0cfebaefabc4a9e552215d73278842e",
          "sha1": "3a2b4466c6a5dd42b131f1a904cfb8ea68fee7d1",
          "md5": "b20c18daeb1e279c33f0f2f0de0840d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.4-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.4-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
