{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.4-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4-1.aar",
          "url": "oboemusicplayerandrecorder-0.5.4-1.aar",
          "size": 1776490,
          "sha512": "55ddec797d314e1d19329a6ea17fd82a843f2d8ca906961fac776a3d4fac0eb695c7ef294d995a8f6c06477df65c75b92d27a231a7f895509f9024ea72aec65e",
          "sha256": "c3f12a5eebdea191f2de22c30e97a1b3658ed4e93aa90c6ed68af2d111641ac4",
          "sha1": "3daa844941a7ca26e2bffdb014927b9c24c6464e",
          "md5": "86f6d5742ad2f245f098e72fcf4193fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4-1.aar",
          "url": "oboemusicplayerandrecorder-0.5.4-1.aar",
          "size": 1776490,
          "sha512": "55ddec797d314e1d19329a6ea17fd82a843f2d8ca906961fac776a3d4fac0eb695c7ef294d995a8f6c06477df65c75b92d27a231a7f895509f9024ea72aec65e",
          "sha256": "c3f12a5eebdea191f2de22c30e97a1b3658ed4e93aa90c6ed68af2d111641ac4",
          "sha1": "3daa844941a7ca26e2bffdb014927b9c24c6464e",
          "md5": "86f6d5742ad2f245f098e72fcf4193fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.4-1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.4-1-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
