{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.10.aar",
          "url": "oboemusicplayerandrecorder-0.6.10.aar",
          "size": 1880106,
          "sha512": "6b37732b090268c2f6028058a023048f7734f36225a7aaba612d2bc952593bfd005307408457c59a23612c54df55df2d27f083e6a046427221cdf92b7cce098c",
          "sha256": "d30f4ae3f4b17828e71d0c577eb7cd3f58c9c9c0b669eb0804011e8556e1634d",
          "sha1": "bc34bd49cabb4c5e4dd6f1241b339347721b2b28",
          "md5": "5ca43b5e203f55e706be372279c43085"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.10.aar",
          "url": "oboemusicplayerandrecorder-0.6.10.aar",
          "size": 1880106,
          "sha512": "6b37732b090268c2f6028058a023048f7734f36225a7aaba612d2bc952593bfd005307408457c59a23612c54df55df2d27f083e6a046427221cdf92b7cce098c",
          "sha256": "d30f4ae3f4b17828e71d0c577eb7cd3f58c9c9c0b669eb0804011e8556e1634d",
          "sha1": "bc34bd49cabb4c5e4dd6f1241b339347721b2b28",
          "md5": "5ca43b5e203f55e706be372279c43085"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.10-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.10-sources.jar",
          "size": 11348,
          "sha512": "e9d315cf5f89a3e4d5d9646cba0adebd32243c31d735c0ec0585408c1f8939017c7f11e6b87977f653e303db12b5419d701d44a44d86a7da5ccf89f694f3debe",
          "sha256": "d80b567591ac2fa0f3c76296d68cb7b74bc83d5acd3155d9bc60b5a8cedc1925",
          "sha1": "83fb3ff53c5afcca85ed969a55d8c211bcba5250",
          "md5": "6281214c1a04e03a2f88ba9d1c795df2"
        }
      ]
    }
  ]
}
