{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.1.aar",
          "url": "oboemusicplayerandrecorder-0.6.1.aar",
          "size": 1779997,
          "sha512": "068187ffd4d2342a762f497992e345d2107239c687487726d5bf5a9d47661aa3f6356e7769301e35163ddfa6741fb3d4a1ed9c2e4e93c75db192a49888d8588b",
          "sha256": "6992976d6bf5b5f03b07260b5fb9e005a971fee77e59b69eca6df1c0ad706aa7",
          "sha1": "1c96ca14b35c4b74453d71b75492d24efccecac2",
          "md5": "4cdb4d863cb839b315ac1274f7ddd8da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.1.aar",
          "url": "oboemusicplayerandrecorder-0.6.1.aar",
          "size": 1779997,
          "sha512": "068187ffd4d2342a762f497992e345d2107239c687487726d5bf5a9d47661aa3f6356e7769301e35163ddfa6741fb3d4a1ed9c2e4e93c75db192a49888d8588b",
          "sha256": "6992976d6bf5b5f03b07260b5fb9e005a971fee77e59b69eca6df1c0ad706aa7",
          "sha1": "1c96ca14b35c4b74453d71b75492d24efccecac2",
          "md5": "4cdb4d863cb839b315ac1274f7ddd8da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.1-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.1-sources.jar",
          "size": 11304,
          "sha512": "58f8f79d857b60e817dec45f9a00c51c884e3ffb0e791c17b4d215fc23ca2d5a973d1be038b3548ba1a28e85343101667e0e2deec73e8245060461044e362f8c",
          "sha256": "c036a58727c4f17dc60385cd49205a8f7e768ac899ac5b5989b7f791fd904520",
          "sha1": "94f889d3626c6563197b4fb05d27c137fe2640c6",
          "md5": "41c77479d3aaeaa5bdc74fd51b071a44"
        }
      ]
    }
  ]
}
