{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-3.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-3.aar",
          "size": 1719954,
          "sha512": "422ed3fd58304ca70a4f52c4e651eabb1c54d9a9b5d9d47ffeb945fa5f757a9e40adea9e3e9f141fea929d3010e099ae488a59412212c288d8bb591444e8a03f",
          "sha256": "bc17f9d1170d0210f00610c519c8d4e3548c553b842a8daa4f481880250c27b7",
          "sha1": "02ef2509aadbd5999fc1f5b774e804743b1a336a",
          "md5": "d651f5150318a00f67d5a3189f18ac72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-3.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-3.aar",
          "size": 1719954,
          "sha512": "422ed3fd58304ca70a4f52c4e651eabb1c54d9a9b5d9d47ffeb945fa5f757a9e40adea9e3e9f141fea929d3010e099ae488a59412212c288d8bb591444e8a03f",
          "sha256": "bc17f9d1170d0210f00610c519c8d4e3548c553b842a8daa4f481880250c27b7",
          "sha1": "02ef2509aadbd5999fc1f5b774e804743b1a336a",
          "md5": "d651f5150318a00f67d5a3189f18ac72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-3-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-3-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
