{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.2.aar",
          "url": "oboemusicplayerandrecorder-0.1.2.aar",
          "size": 1393708,
          "sha512": "30e542e8f129b71e048b5278f4eaedd8ee812ff038be30d774f7804b43297c26922abf44a0a5edded83856a2a3ce340226b274ba3dc79efe50b0ba76b10f3f2d",
          "sha256": "70bbc6c7bf30bdd7c7807b725d87a7152262e983a1245599ebc3fc770997a19e",
          "sha1": "3e6507dd7ce2ebcb4781b86dd135840edf0c71d3",
          "md5": "0e608c31816cd0f16a6f828d96a5d655"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.2.aar",
          "url": "oboemusicplayerandrecorder-0.1.2.aar",
          "size": 1393708,
          "sha512": "30e542e8f129b71e048b5278f4eaedd8ee812ff038be30d774f7804b43297c26922abf44a0a5edded83856a2a3ce340226b274ba3dc79efe50b0ba76b10f3f2d",
          "sha256": "70bbc6c7bf30bdd7c7807b725d87a7152262e983a1245599ebc3fc770997a19e",
          "sha1": "3e6507dd7ce2ebcb4781b86dd135840edf0c71d3",
          "md5": "0e608c31816cd0f16a6f828d96a5d655"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.1.2-sources.jar",
          "url": "oboemusicplayerandrecorder-0.1.2-sources.jar",
          "size": 3793,
          "sha512": "c832beb087193d87f6a9eaadd578110cd9b390d7d95f9b35aae55b6b2a71d2e2726fad5aebb65560c8257ff8ad9ef4182919a980ac9b2cd9bd57273447ce9388",
          "sha256": "3c20d5df961017a9b8eb42ead9df3c9cbfb4417621d916b03af597ed3aa5f7d3",
          "sha1": "33a28da687d1bdc3cf5d31460da074b04ca5eaa0",
          "md5": "bbf5f2c643d78b06bbd53854996c5865"
        }
      ]
    }
  ]
}
