{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.2.5-exp8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp8.aar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp8.aar",
          "size": 1664684,
          "sha512": "6e77ec552b86434a9e4d404e02a50f8f4b72b55ed9b69850da158dfd0ef5bb14821355a8e2ab497196240368916f23ad17bb7b753695ea07114153aca0ba0cf1",
          "sha256": "b8531adf48d8f5a592c6e5976796941be5c1d3fb4daaca199ede2b9ac7b1f329",
          "sha1": "dbc04a3917807e5738dac7e0b3fd84610e6a1cb1",
          "md5": "0e2573b736f983f00624a877a8401892"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp8.aar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp8.aar",
          "size": 1664684,
          "sha512": "6e77ec552b86434a9e4d404e02a50f8f4b72b55ed9b69850da158dfd0ef5bb14821355a8e2ab497196240368916f23ad17bb7b753695ea07114153aca0ba0cf1",
          "sha256": "b8531adf48d8f5a592c6e5976796941be5c1d3fb4daaca199ede2b9ac7b1f329",
          "sha1": "dbc04a3917807e5738dac7e0b3fd84610e6a1cb1",
          "md5": "0e2573b736f983f00624a877a8401892"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.2.5-exp8-sources.jar",
          "url": "oboemusicplayerandrecorder-0.2.5-exp8-sources.jar",
          "size": 8084,
          "sha512": "1f98436c26f4fc8b19bce66d212db6c50bd3deecee27bf2f50306df77f483f9d95810d4a9906a13ba0eb1c5b0a1023cbc63ea2deb04c2db12617bd475e031283",
          "sha256": "caa25b78a9ca4006cc8582ef4dbdc467ba675d05bf845adb8b76c0f8523f9cf9",
          "sha1": "e9f2c47eb023465b2d442d0ad6dccfbf4f53725f",
          "md5": "3389cb436eaf52c76f79dde4e44a292b"
        }
      ]
    }
  ]
}
