{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.6.6-EXP-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.6-EXP-4.aar",
          "url": "oboemusicplayerandrecorder-0.6.6-EXP-4.aar",
          "size": 1806261,
          "sha512": "e804840f429ff5b627cad80d9ef20f91ec1799a2db28146f364c6ed8545e5e63e2df825d0cfd6c0d0fc64f520150331b2d836e12dd3311d10f1affda1051e890",
          "sha256": "b660d4c91f8347522654b05d4b9a5306949c75679c4a925f5c7c8b384b4e061d",
          "sha1": "c635afbbebc56f93ff786ba5ee13b6b07b954201",
          "md5": "dff7d8aaf2823e27d2ea91d50fefddc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.6-EXP-4.aar",
          "url": "oboemusicplayerandrecorder-0.6.6-EXP-4.aar",
          "size": 1806261,
          "sha512": "e804840f429ff5b627cad80d9ef20f91ec1799a2db28146f364c6ed8545e5e63e2df825d0cfd6c0d0fc64f520150331b2d836e12dd3311d10f1affda1051e890",
          "sha256": "b660d4c91f8347522654b05d4b9a5306949c75679c4a925f5c7c8b384b4e061d",
          "sha1": "c635afbbebc56f93ff786ba5ee13b6b07b954201",
          "md5": "dff7d8aaf2823e27d2ea91d50fefddc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.6.6-EXP-4-sources.jar",
          "url": "oboemusicplayerandrecorder-0.6.6-EXP-4-sources.jar",
          "size": 11985,
          "sha512": "112ec5bc19c21ab984afe3f90962663a8e0c1f7f97fcc23adef3f63c9668fdd05022f699b16d16cfe26bdfd5765f6c9a867203a5665b0ae25a8ff8f9c1d9498e",
          "sha256": "2f67437f0a2bebcc95478f37edbfb13a580ed012994bdbe5802148101d130770",
          "sha1": "0be69c35a4ab5ffd03c2e70517e8472210ffd82c",
          "md5": "403839f1ac66cedfd4efcdc93c95561b"
        }
      ]
    }
  ]
}
