{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.1-exp6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp6.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp6.aar",
          "size": 1774132,
          "sha512": "72130812da3d6d0c9737d03b323d4e1db94db1f16e2c9f273f903f1959fa5271b3b693674decfb3e948750f3a3b50c59cfa17533ce35a64987fe30a6e9031758",
          "sha256": "8bcadf9547762fa7df91fa312cd08d19abb201742a57e4fa4eea70ce64b5b39d",
          "sha1": "4d6a5ca395c9703739a23ff86156676908e24d95",
          "md5": "bc0d2ea3d84f7f8c015b18ea388ff0bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp6.aar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp6.aar",
          "size": 1774132,
          "sha512": "72130812da3d6d0c9737d03b323d4e1db94db1f16e2c9f273f903f1959fa5271b3b693674decfb3e948750f3a3b50c59cfa17533ce35a64987fe30a6e9031758",
          "sha256": "8bcadf9547762fa7df91fa312cd08d19abb201742a57e4fa4eea70ce64b5b39d",
          "sha1": "4d6a5ca395c9703739a23ff86156676908e24d95",
          "md5": "bc0d2ea3d84f7f8c015b18ea388ff0bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.1-exp6-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.1-exp6-sources.jar",
          "size": 14588,
          "sha512": "1972909aa7b358d6fb00c52a7af875c2863cd96344328e05bcfa675c7232cac3b2e39e8340c5de0bd753aa49b948c2c9f0ab8b922ab3e6736bb93c01f4d9a44d",
          "sha256": "dfef059fdc2245b2ed68b4539ca05c2ba7a24e55a711412b5b414d05478d5125",
          "sha1": "dfb065886bf97f03a8ba96b885c5c7575123bb43",
          "md5": "3cff69301c2c294f3614ebeeb7fa0b07"
        }
      ]
    }
  ]
}
