{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.8.aar",
          "url": "oboemusicplayerandrecorder-0.4.8.aar",
          "size": 1775102,
          "sha512": "63298a930caeca83866707bfcd1e33f65aa56e061af37de532547c864cf1ae1f4d24f7d1c4c11bffeefbe0c804802b2b40adf9f6fa257781e9af5b15f066dd7e",
          "sha256": "dba2b094c465e5f3fde9b80b7bd481a87cfb6b2c0bd18cfbba9387b1097fba66",
          "sha1": "0df54c43542e9138a184506a633f39ddaf6e37ba",
          "md5": "cd41a8ea6febe6b5a393155e14678feb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.8.aar",
          "url": "oboemusicplayerandrecorder-0.4.8.aar",
          "size": 1775102,
          "sha512": "63298a930caeca83866707bfcd1e33f65aa56e061af37de532547c864cf1ae1f4d24f7d1c4c11bffeefbe0c804802b2b40adf9f6fa257781e9af5b15f066dd7e",
          "sha256": "dba2b094c465e5f3fde9b80b7bd481a87cfb6b2c0bd18cfbba9387b1097fba66",
          "sha1": "0df54c43542e9138a184506a633f39ddaf6e37ba",
          "md5": "cd41a8ea6febe6b5a393155e14678feb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.4.8-sources.jar",
          "url": "oboemusicplayerandrecorder-0.4.8-sources.jar",
          "size": 11260,
          "sha512": "2654e63ad96b46efcd77a9d6d5b7b12ba40a2e1577600a09b0e4a0493c836c5a0092c6795a94a6a58ffa55bebcf4ef0b9acc7a4890ba1c4edd67efcd7d645091",
          "sha256": "d02f6682faaa265304b0a5581115ce277039a1b7dc364a79d7775cd62eba11d2",
          "sha1": "678bc54cf39b2722f3e1709a55c44b495b987b9c",
          "md5": "6cd1203c460064efcdb6acc32cb6e1da"
        }
      ]
    }
  ]
}
