{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.0.aar",
          "url": "oboemusicplayerandrecorder-0.5.0.aar",
          "size": 1774222,
          "sha512": "61ac7426e9dd6ccee830cd97cabd6a72904c37dd4ad82e6e9d5bf57f35b78ca79d93e6193428c2848c32b5e458ca88a42fc24255cf74c8dca336e778320eddfc",
          "sha256": "3f420943666c3941d24c64033fed8377a94c16eb4dbe268a9b65547e0fccb92c",
          "sha1": "17744374d0dd129b694ba88c41e5d58cf7d0e5b5",
          "md5": "781c7ae22e818622ba68c05172c6cf14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.0.aar",
          "url": "oboemusicplayerandrecorder-0.5.0.aar",
          "size": 1774222,
          "sha512": "61ac7426e9dd6ccee830cd97cabd6a72904c37dd4ad82e6e9d5bf57f35b78ca79d93e6193428c2848c32b5e458ca88a42fc24255cf74c8dca336e778320eddfc",
          "sha256": "3f420943666c3941d24c64033fed8377a94c16eb4dbe268a9b65547e0fccb92c",
          "sha1": "17744374d0dd129b694ba88c41e5d58cf7d0e5b5",
          "md5": "781c7ae22e818622ba68c05172c6cf14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.5.0-sources.jar",
          "url": "oboemusicplayerandrecorder-0.5.0-sources.jar",
          "size": 14637,
          "sha512": "92eef37dc8033b5abce2a7b67a4385db0fa512972070d8541a1d1470c21a7a793ae70b201349a89b8642efaa29564d6b9b3e076a426bd09edc8372d26b7c3de6",
          "sha256": "65dbcb07693cb1ab0c7d2cdc493652eaffdf0eb29e74eee16c6cc3d2e69e20cc",
          "sha1": "463b21e0a67edda8d15202b041e256a6909930ab",
          "md5": "2f4fb090de0318eee46fd67b056cbe82"
        }
      ]
    }
  ]
}
