{
  "formatVersion": "1.1",
  "component": {
    "group": "in.reconv",
    "module": "oboemusicplayerandrecorder",
    "version": "0.3.5-exp16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp16.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp16.aar",
          "size": 2522608,
          "sha512": "28c7e922d4c8677981d4c64bc0f21b3db0b016b65191994c3b3b17f82851319b2ce7b4024e151a41dcf1bff2a60b1f6ccf060ed078e68dbc60314b710b77096b",
          "sha256": "6dbbca7617ea4ba6bec493511a280aefd1eeaf5b19c1bfe450694b1b07aae4cf",
          "sha1": "2a40abd88ceab8d702a41fbb303c4bc11891e720",
          "md5": "8891d2b6025441108f6b37cc4a9a40d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp16.aar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp16.aar",
          "size": 2522608,
          "sha512": "28c7e922d4c8677981d4c64bc0f21b3db0b016b65191994c3b3b17f82851319b2ce7b4024e151a41dcf1bff2a60b1f6ccf060ed078e68dbc60314b710b77096b",
          "sha256": "6dbbca7617ea4ba6bec493511a280aefd1eeaf5b19c1bfe450694b1b07aae4cf",
          "sha1": "2a40abd88ceab8d702a41fbb303c4bc11891e720",
          "md5": "8891d2b6025441108f6b37cc4a9a40d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oboemusicplayerandrecorder-0.3.5-exp16-sources.jar",
          "url": "oboemusicplayerandrecorder-0.3.5-exp16-sources.jar",
          "size": 9470,
          "sha512": "03d935542a88b1caaab4d18c6dc33132055862749bbb7936d8395dc9a3f2cb6ab4270e998b0e49082f5b96085f65db0645204a1eedb7fbe1bde6e2b46d022c0c",
          "sha256": "3e32cf2df6ebcae50cdaacaad37d0441ed4ab09b1d432e794a258513cfc36bad",
          "sha1": "9b1ad03e4aff6883fe8f71ab6902c822268d5758",
          "md5": "f863bb0a75204b81c68f759999a6cbed"
        }
      ]
    }
  ]
}
